using System.Collections.Immutable;
using System.Linq;
using System.Threading;

namespace SparseFragments.Generator.Shared;

/// <summary>Per-model Patch/ChangeSet implementation file shell.</summary>
/// <remarks>
/// Issue #194 relocates model-specific Patch and ChangeSet algorithms into
/// an external per-model operation container while the model keeps thin
/// typed facades. This emitter writes the implementation file envelope
/// (header, facade aliases, namespace, per-model container and operation
/// class frames); the algorithm bodies themselves stream into the provided
/// builders through the existing Patch/ChangeSet emitters with a
/// <see cref="SparseOperationTarget"/>. Placement and hint names resolve
/// through <see cref="SparseGeneratedPlacement"/> with no product literals.
/// </remarks>
internal static class SparseModelOperationFileEmitter
{
    /// <summary>Opens the implementation file and the patch operation container.</summary>
    /// <param name="code">Implementation file builder (offset for container depth).</param>
    /// <param name="model">Model identity.</param>
    /// <param name="modelType">Qualified model type name.</param>
    /// <param name="members">Analyzed members.</param>
    /// <param name="dialect">Product patch dialect.</param>
    /// <param name="plan">Effective emission features.</param>
    /// <param name="implementationNamespace">Explicit implementation namespace.</param>
    /// <param name="container">Per-model implementation container name.</param>
    /// <param name="canApplyPatchInPlace">Whether the patch in-place result exists.</param>
    /// <param name="cancellationToken">Cooperative cancellation.</param>
    public static void OpenImplementation(
        SharedIndentedBuilder code,
        SparseModelInfo model,
        string modelType,
        ImmutableArray<SparseMemberModel> members,
        SparseFragmentPatchEmitter.SparsePatchDialect dialect,
        SparseEmissionFeatures plan,
        string implementationNamespace,
        string container,
        bool canApplyPatchInPlace,
        CancellationToken cancellationToken
    )
    {
        _ = cancellationToken;
        code.AppendLine("// <auto-generated />");
        code.AppendLine("#nullable enable");
        if (HasNullableKeyedMember(members))
        {
            code.AppendLine(
                "#pragma warning disable CS8714 // Present nullable values are valid dictionary keys."
            );
        }
        SparseModelOperationAliases.Append(
            code,
            SparseModelOperationAliases.Collect(
                modelType,
                members,
                dialect,
                plan,
                canApplyPatchInPlace
            )
        );
        code.AppendLine();
        code.Append("namespace ").Append(implementationNamespace).AppendLine();
        code.AppendLine("{");
        var accessibility = model.IsPublic ? "public" : "internal";
        code.AppendLineAt(
            1,
            "/// <summary>Per-model generated operations for '"
                + modelType
                + "'. Backs the model-facing Patch and ChangeSet facades.</summary>"
        );
        code.AppendLineAt(1, accessibility + " static partial class " + container);
        code.AppendLineAt(1, "{");
    }

    /// <summary>Opens one operation container class.</summary>
    /// <param name="code">Implementation file builder.</param>
    /// <param name="simpleName">Operation class simple name.</param>
    /// <param name="backedFacade">Backed facade description for docs.</param>
    public static void OpenOperations(
        SharedIndentedBuilder code,
        string simpleName,
        string backedFacade
    )
    {
        code.AppendLineAt(
            2,
            "/// <summary>Model-specific "
                + backedFacade
                + " algorithms backing the thin model facade.</summary>"
        );
        code.AppendLineAt(2, "internal static class " + simpleName);
        code.AppendLineAt(2, "{");
    }

    /// <summary>Closes one operation container class.</summary>
    /// <param name="code">Implementation file builder.</param>
    public static void CloseOperations(SharedIndentedBuilder code) => code.AppendLineAt(2, "}");

    /// <summary>Closes the per-model container and its namespace.</summary>
    /// <param name="code">Implementation file builder.</param>
    public static void CloseImplementation(SharedIndentedBuilder code)
    {
        code.AppendLineAt(1, "}");
        code.AppendLine("}");
    }

    private static bool HasNullableKeyedMember(ImmutableArray<SparseMemberModel> members) =>
        members.Any(static member =>
            SparseKeyedCollectionEmitter.IsKeyedSequence(member)
            && member.Collection.KeyTypeName?.EndsWith("?", System.StringComparison.Ordinal) == true
        );
}
