<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>SparseFragments.Blazor.Tests</RootNamespace>
    <AssemblyName>SparseFragments.Blazor.Tests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/SparseFragments.Blazor/SparseFragments.Blazor.csproj" />
    <ProjectReference Include="../../src/SparseFragments/SparseFragments.csproj" />
    <ProjectReference
      Include="../../src/SparseFragments.Generator/SparseFragments.Generator.csproj"
      OutputItemType="Analyzer"
      ReferenceOutputAssembly="true"
    />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Shouldly" />
    <Using Include="SparseFragments" />
    <Using Include="SparseFragments.Blazor" />
  </ItemGroup>
</Project>
