<Project>
  <PropertyGroup>
    <LangVersion>preview</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <MSBuildTreatAllWarningsAsErrors>true</MSBuildTreatAllWarningsAsErrors>
    <RestoreTreatWarningsAsErrors>true</RestoreTreatWarningsAsErrors>
    <AnalysisLevel>latest</AnalysisLevel>
    <GenerateDocumentationFile Condition="'$(SparseSharedOnly)' != 'true'">true</GenerateDocumentationFile>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/arika0093/SparseFragments</RepositoryUrl>
    <PackageProjectUrl>https://github.com/arika0093/SparseFragments</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PolyArgumentExceptions>true</PolyArgumentExceptions>
    <PolyUseEmbeddedAttribute>true</PolyUseEmbeddedAttribute>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Nerdbank.GitVersioning" Version="3.*" PrivateAssets="all">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="CSharpier.MsBuild" Version="1.3.0" PrivateAssets="all">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="SonarAnalyzer.CSharp" Version="10.*" PrivateAssets="all">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" PackagePath="/" />
  </ItemGroup>
</Project>
