using System.Collections.Immutable;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading;

namespace SparseFragments.Generator.Shared;

/// <summary>Builds the relocated per-model descriptor factory.</summary>
/// <remarks>
/// Reuses the existing descriptor emitters for the graph body, then rewrites
/// instance access from <c>this</c> to the factory <c>observable</c> parameter
/// and child proxy accessors to child factories. Internal observable bridges
/// (`__model`, `__onChanged`, `__onRawModelAccess`, `__Raise`) stay in the
/// same assembly so the factory binds live state without public surface.
/// </remarks>
internal static class SparseDescriptorFactoryEmitter
{
    /// <summary>Builds the descriptor-factory additional source.</summary>
    /// <param name="model">Owning model.</param>
    /// <param name="members">Analyzed members.</param>
    /// <param name="config">Owning generator configuration.</param>
    /// <param name="cancellationToken">Cooperative cancellation.</param>
    /// <param name="runtimeNamespace">Runtime helper namespace.</param>
    /// <returns>Additional source with a distinct hint.</returns>
    public static SparseGeneratedSource BuildSource(
        SparseModelInfo model,
        ImmutableArray<SparseMemberModel> members,
        SparseGeneratorConfig config,
        CancellationToken cancellationToken,
        string runtimeNamespace
    )
    {
        var dialect =
            config.DescriptorDialect
            ?? throw new System.ArgumentException(
                "A descriptor dialect is required.",
                nameof(config)
            );
        var innerBuilder = new SharedIndentedBuilder(cancellationToken);
        SparseObservableDescriptorEmitter.Append(
            innerBuilder,
            model.ModelTypeName,
            members,
            runtimeNamespace,
            dialect
        );
        var legacy = innerBuilder.ToString();
        var relocated = SparseModelImplementationEmitter.RelocateUiReferences(
            legacy,
            model.ModelTypeName,
            members,
            ImmutableArray<SparseReadOnlyViewModel>.Empty,
            config,
            cancellationToken
        );
        var body = RewriteReceiver(relocated);
        // Legacy emits "internal IDescriptorSet __SparseGetDescriptors_<hash>(string pathPrefix) { ... }".
        // The factory exposes a stable per-model Create entry instead.
        body = Regex.Replace(
            body,
            @"internal\s+\S+\s+__SparseGetDescriptors_[0-9A-F]{8}\s*\(\s*string\s+pathPrefix\s*\)",
            "internal static "
                + dialect.DescriptorSetInterface
                + " Create("
                + ObservableParam(model, members, config, cancellationToken)
                + " observable, string pathPrefix)",
            RegexOptions.None,
            System.TimeSpan.FromSeconds(1)
        );
        var family = config.EffectiveFamilyNames;
        var observableSimple = SparseObservableEmitter.ObservableTypeName(members, family);
        var code = new SharedIndentedBuilder(cancellationToken);
        code.AppendLine("// <auto-generated />");
        code.AppendLine("#nullable enable");
        var root =
            SparseGeneratedPlacement.TryGetImplementationNamespace(config)
            ?? throw new System.ArgumentException(
                "An implementation namespace is required.",
                nameof(config)
            );
        var container = SparseGeneratedPlacement.GetImplementationContainer(
            model,
            cancellationToken
        );
        var accessibility = model.IsPublic ? "public" : "internal";
        code.Append("namespace ").Append(root).AppendLine();
        code.AppendLine("{");
        code.AppendLineAt(1, "/// <summary>Live descriptor bindings for one model.</summary>");
        code.AppendLineAt(1, accessibility + " partial class " + container);
        code.AppendLineAt(1, "{");
        code.AppendLineAt(
            2,
            "/// <summary>Descriptor factory bound to the owning observable.</summary>"
        );
        code.AppendLineAt(2, "internal static class DescriptorFactory");
        code.AppendLineAt(2, "{");
        code.Append(body);
        code.AppendLineAt(2, "}");
        code.AppendLineAt(1, "}");
        code.AppendLine("}");
        // Fix indentation: legacy body used indent 2/3/4 for nested Observable;
        // inside "namespace/container/factory" it needs one extra level. The
        // code still compiles with the old indents, so keep the body as-is to
        // avoid reflowing generated text.
        _ = observableSimple;
        var source = code.ToString();
        return new SparseGeneratedSource(
            SparseGeneratedPlacement.DescriptorFactoryHintName(model, cancellationToken),
            source
        );
    }

    private static string ObservableParam(
        SparseModelInfo model,
        ImmutableArray<SparseMemberModel> members,
        SparseGeneratorConfig config,
        CancellationToken cancellationToken
    )
    {
        var family = config.EffectiveFamilyNames;
        var simple = SparseObservableEmitter.ObservableTypeName(members, family);
        return SparseGeneratedPlacement.GetObservableReference(
            model,
            simple,
            config,
            cancellationToken
        );
    }

    private static string RewriteReceiver(string source)
    {
        // Instance state moves from "this" to the factory parameter. Order
        // matters: longer names first so "__onRawModelAccess" does not get a
        // partial "__model" rewrite. Child proxy accessors stay as
        // "current.__SparseGet_X(path)": each relocated Observable keeps a
        // thin bridge delegating to its own factory.
        source = source.Replace("this.", "observable.");
        source = source.Replace("__onRawModelAccess", "observable.__onRawModelAccess");
        source = source.Replace("__onChanged", "observable.__onChanged");
        source = source.Replace("__Raise(", "observable.__Raise(");
        source = source.Replace("__model.", "observable.__model.");
        return source;
    }
}
