using System;
using System.Threading;

namespace SparseFragments.Generator.Shared;

/// <summary>Compilation-scoped Generated-Once emission plane.</summary>
/// <remarks>
/// Helpers here are model-independent, emitted once per consumer
/// compilation, and normally <c>internal</c>: they implement product
/// runtime contracts but never escape through public signatures. Per-model
/// output calls into these helpers; <see cref="SparsePerModelEmitter"/>
/// owns the per-model plane. Hint names and type identities derive from
/// the owning generator configuration so coexisting products stay distinct.
/// </remarks>
internal static class SparseGeneratedOnceEmitter
{
    /// <summary>Simple name of the shared clone helper container.</summary>
    public const string CloneHelpersTypeName = "SparseCloneHelpers";

    /// <summary>Simple name of the shared read-only list adapter.</summary>
    public const string ReadOnlyListAdapterTypeName = "SparseReadOnlyListAdapter";

    /// <summary>Simple name of the shared read-only dictionary adapter.</summary>
    public const string ReadOnlyDictionaryAdapterTypeName = "SparseReadOnlyDictionaryAdapter";

    /// <summary>Simple name of the shared read-only dictionary entries adapter.</summary>
    public const string ReadOnlyDictionaryEntriesAdapterTypeName =
        "SparseReadOnlyDictionaryEntriesAdapter";

    /// <summary>Simple name of the shared removal-index helper.</summary>
    public const string RemovalIndexTypeName = "SparseRemovalIndex";

    /// <summary>Gets the stable hint name for the clone helper source.</summary>
    /// <param name="implementationNamespace">Owning generator implementation namespace.</param>
    /// <returns>A stable unique hint name.</returns>
    public static string CloneHelpersHintName(string implementationNamespace) =>
        implementationNamespace + ".CloneHelpers.g.cs";

    /// <summary>Gets the stable hint name for the read-only adapter source.</summary>
    /// <param name="implementationNamespace">Owning generator implementation namespace.</param>
    /// <returns>A stable unique hint name.</returns>
    public static string ReadOnlyAdaptersHintName(string implementationNamespace) =>
        implementationNamespace + ".ReadOnlyAdapters.g.cs";

    /// <summary>Gets the stable hint name for the removal-index source.</summary>
    /// <param name="implementationNamespace">Owning generator implementation namespace.</param>
    /// <returns>A stable unique hint name.</returns>
    public static string RemovalIndexHintName(string implementationNamespace) =>
        implementationNamespace + ".RemovalIndex.g.cs";

    /// <summary>Resolves the implementation namespace, or null when disabled.</summary>
    /// <param name="config">Owning generator configuration.</param>
    /// <returns>The explicit namespace, or null for no Generated-Once output.</returns>
    public static string? TryGetNamespace(SparseGeneratorConfig config) =>
        SparseGeneratedPlacement.TryGetImplementationNamespace(config);

    /// <summary>Renders the shared clone helper source.</summary>
    /// <param name="implementationNamespace">Owning generator implementation namespace.</param>
    /// <param name="includePortableSetView">Target-framework set-view variant.</param>
    /// <param name="hashSetSupportsCapacity">Target-framework capacity support.</param>
    /// <param name="cancellationToken">Cooperative cancellation.</param>
    /// <returns>Model-independent helper source.</returns>
    public static string RenderCloneHelpers(
        string implementationNamespace,
        bool includePortableSetView,
        bool hashSetSupportsCapacity,
        CancellationToken cancellationToken
    )
    {
        var inner = new SharedIndentedBuilder(cancellationToken);
        SparseFragmentCollectionCloneEmitter.AppendCollectionCloneHelpers(
            inner,
            includePortableSetView,
            hashSetSupportsCapacity
        );
        // The per-model emitter owns private helpers; the shared plane
        // exposes the same generic bodies as internal static members so
        // per-model code can call them without re-emitting the logic.
        var body = inner
            .ToString()
            .Replace("private static ", "internal static ")
            .Replace("private sealed class ", "internal sealed class ");

        var code = new SharedIndentedBuilder(cancellationToken);
        code.AppendLine("// <auto-generated />");
        code.AppendLine("#nullable enable");
        code.Append("namespace ").Append(implementationNamespace).AppendLine();
        code.AppendLine("{");
        code.AppendLineAt(
            1,
            "/// <summary>Shared collection clone helpers emitted once per compilation.</summary>"
        );
        code.AppendLineAt(1, "internal static class " + CloneHelpersTypeName);
        code.AppendLineAt(1, "{");
        foreach (var line in body.Split('\n'))
        {
            cancellationToken.ThrowIfCancellationRequested();
            if (line.Length == 0)
            {
                code.AppendLine();
            }
            else
            {
                code.AppendLineAt(2, line.TrimStart());
            }
        }

        code.AppendLineAt(1, "}");
        code.AppendLine("}");
        return code.ToString();
    }

    /// <summary>Renders the shared read-only adapter source.</summary>
    /// <param name="implementationNamespace">Owning generator implementation namespace.</param>
    /// <param name="cancellationToken">Cooperative cancellation.</param>
    /// <returns>Model-independent adapter source using only BCL types.</returns>
    public static string RenderReadOnlyAdapters(
        string implementationNamespace,
        CancellationToken cancellationToken
    )
    {
        var code = new SharedIndentedBuilder(cancellationToken);
        code.AppendLine("// <auto-generated />");
        code.AppendLine("#nullable enable");
        code.Append("namespace ").Append(implementationNamespace).AppendLine();
        code.AppendLine("{");
        code.AppendLineAt(
            1,
            "/// <summary>Shared streaming read-only adapters emitted once per compilation.</summary>"
        );
        AppendAdapter(
            code,
            ReadOnlyListAdapterTypeName,
            static (builder, name) =>
                SparseReadOnlyAdapterEmitter.AppendCollectionAdapter(builder, name),
            cancellationToken
        );
        AppendAdapter(
            code,
            ReadOnlyDictionaryAdapterTypeName,
            static (builder, name) =>
                SparseReadOnlyAdapterEmitter.AppendDictionaryAdapter(
                    builder,
                    name,
                    ReadOnlyListAdapterTypeName
                ),
            cancellationToken
        );
        code.AppendLineAt(
            1,
            "/// <summary>Streaming entries view over a read-only dictionary source.</summary>"
        );
        var entries = new SharedIndentedBuilder(cancellationToken);
        SparseReadOnlyAdapterEmitter.AppendDictionaryEntriesAdapter(entries, "__SparseEntries");
        var entriesBody = entries
            .ToString()
            .Replace(
                "private sealed class __SparseEntries",
                "internal sealed class " + ReadOnlyDictionaryEntriesAdapterTypeName
            )
            .Replace(
                "public __SparseEntries(",
                "public " + ReadOnlyDictionaryEntriesAdapterTypeName + "("
            );
        foreach (var line in entriesBody.Split('\n'))
        {
            cancellationToken.ThrowIfCancellationRequested();
            if (line.Length == 0)
            {
                code.AppendLine();
            }
            else
            {
                code.AppendLine(line.TrimStart());
            }
        }

        code.AppendLine("}");
        return code.ToString();
    }

    /// <summary>Renders the shared removal-index helper source.</summary>
    /// <param name="implementationNamespace">Owning generator implementation namespace.</param>
    /// <param name="cancellationToken">Cooperative cancellation.</param>
    /// <returns>Generic index helpers over caller-owned removal lists.</returns>
    public static string RenderRemovalIndex(
        string implementationNamespace,
        CancellationToken cancellationToken
    )
    {
        // Generic over the key with the BCL default comparer: per-patch
        // removal lists already key on EqualityComparer{TKey}.Default, so
        // the shared helper stays model-independent and runtime-neutral.
        var code = new SharedIndentedBuilder(cancellationToken);
        code.AppendLine("// <auto-generated />");
        code.AppendLine("#nullable enable");
        code.Append("namespace ").Append(implementationNamespace).AppendLine();
        code.AppendLine("{");
        code.AppendLineAt(
            1,
            "/// <summary>Shared ordered-removal index helpers emitted once per compilation.</summary>"
        );
        code.AppendLineAt(1, "internal static class " + RemovalIndexTypeName + "<TKey>");
        code.AppendLineAt(1, "{");
        code.AppendLineAt(
            2,
            "private static global::System.Collections.Generic.IEqualityComparer<TKey> Comparer => global::System.Collections.Generic.EqualityComparer<TKey>.Default;"
        );
        code.AppendLineAt(
            2,
            "internal static void CancelRemoval(global::System.Collections.Generic.List<TKey> removed, TKey key, ref int[]? lookup)"
        );
        code.AppendLineAt(2, "{");
        code.AppendLineAt(3, "for (int index = removed.Count - 1; index >= 0; index--)");
        code.AppendLineAt(3, "{");
        code.AppendLineAt(4, "if (!Comparer.Equals(removed[index], key)) continue;");
        code.AppendLineAt(4, "removed.RemoveAt(index);");
        code.AppendLineAt(4, "lookup = null;");
        code.AppendLineAt(3, "}");
        code.AppendLineAt(2, "}");
        code.AppendLineAt(
            2,
            "internal static bool ContainsRemoved(global::System.Collections.Generic.List<TKey> removed, TKey key, int[]? lookup)"
        );
        code.AppendLineAt(2, "{");
        code.AppendLineAt(
            3,
            "if (lookup is not null) return lookup[RemovedSlot(removed, key, lookup)] != 0;"
        );
        code.AppendLineAt(3, "foreach (var existing in removed)");
        code.AppendLineAt(3, "{");
        code.AppendLineAt(4, "if (Comparer.Equals(existing, key)) return true;");
        code.AppendLineAt(3, "}");
        code.AppendLineAt(3, "return false;");
        code.AppendLineAt(2, "}");
        code.AppendLineAt(
            2,
            "internal static int RemovedSlot(global::System.Collections.Generic.List<TKey> removed, TKey key, int[] slots)"
        );
        code.AppendLineAt(2, "{");
        code.AppendLineAt(3, "int mask = slots.Length - 1;");
        code.AppendLineAt(3, "int slot = Comparer.GetHashCode(key!) & mask;");
        code.AppendLineAt(
            3,
            "while (slots[slot] != 0 && !Comparer.Equals(removed[slots[slot] - 1], key))"
        );
        code.AppendLineAt(3, "{");
        code.AppendLineAt(4, "slot = (slot + 1) & mask;");
        code.AppendLineAt(3, "}");
        code.AppendLineAt(3, "return slot;");
        code.AppendLineAt(2, "}");
        code.AppendLineAt(
            2,
            "internal static int[] RebuildIndex(global::System.Collections.Generic.List<TKey> removed, int capacity)"
        );
        code.AppendLineAt(2, "{");
        code.AppendLineAt(3, "var slots = new int[capacity];");
        code.AppendLineAt(3, "for (int index = 0; index < removed.Count; index++)");
        code.AppendLineAt(3, "{");
        code.AppendLineAt(4, "slots[RemovedSlot(removed, removed[index], slots)] = index + 1;");
        code.AppendLineAt(3, "}");
        code.AppendLineAt(3, "return slots;");
        code.AppendLineAt(2, "}");
        code.AppendLineAt(
            2,
            "internal static void Reserve(global::System.Collections.Generic.List<TKey> removed, int count, ref int[]? lookup)"
        );
        code.AppendLineAt(2, "{");
        code.AppendLineAt(3, "if (count < 32) return;");
        code.AppendLineAt(3, "int capacity = 64;");
        code.AppendLineAt(
            3,
            "while (capacity < checked(count * 2)) capacity = checked(capacity * 2);"
        );
        code.AppendLineAt(3, "lookup = RebuildIndex(removed, capacity);");
        code.AppendLineAt(2, "}");
        code.AppendLineAt(
            2,
            "internal static void AddIndexed(global::System.Collections.Generic.List<TKey> removed, TKey key, ref int[]? lookup)"
        );
        code.AppendLineAt(2, "{");
        code.AppendLineAt(3, "var slots = lookup;");
        code.AppendLineAt(3, "if (slots is null)");
        code.AppendLineAt(3, "{");
        code.AppendLineAt(4, "int capacity = 64;");
        code.AppendLineAt(
            4,
            "while (capacity <= checked(removed.Count * 2)) capacity = checked(capacity * 2);"
        );
        code.AppendLineAt(4, "slots = RebuildIndex(removed, capacity);");
        code.AppendLineAt(4, "lookup = slots;");
        code.AppendLineAt(3, "}");
        code.AppendLineAt(3, "int slot = RemovedSlot(removed, key, slots);");
        code.AppendLineAt(3, "if (slots[slot] != 0) return;");
        code.AppendLineAt(3, "if (removed.Count >= slots.Length / 2)");
        code.AppendLineAt(3, "{");
        code.AppendLineAt(4, "slots = RebuildIndex(removed, checked(slots.Length * 2));");
        code.AppendLineAt(4, "lookup = slots;");
        code.AppendLineAt(4, "slot = RemovedSlot(removed, key, slots);");
        code.AppendLineAt(3, "}");
        code.AppendLineAt(3, "removed.Add(key);");
        code.AppendLineAt(3, "slots[slot] = removed.Count;");
        code.AppendLineAt(2, "}");
        code.AppendLineAt(1, "}");
        code.AppendLine("}");
        return code.ToString();
    }

    private static void AppendAdapter(
        SharedIndentedBuilder code,
        string typeName,
        Action<SharedIndentedBuilder, string> append,
        CancellationToken cancellationToken
    )
    {
        var inner = new SharedIndentedBuilder(cancellationToken);
        append(inner, "__SparseAdapter");
        var body = inner
            .ToString()
            .Replace("private sealed class __SparseAdapter", "internal sealed class " + typeName)
            .Replace("public __SparseAdapter(", "public " + typeName + "(");
        foreach (var line in body.Split('\n'))
        {
            cancellationToken.ThrowIfCancellationRequested();
            if (line.Length == 0)
            {
                code.AppendLine();
            }
            else
            {
                code.AppendLine(line.TrimStart());
            }
        }
    }
}
