<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <RunAnalyzersDuringLiveAnalysis>false</RunAnalyzersDuringLiveAnalysis>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
    <ProjectReference Include="../../src/SparseFragments/SparseFragments.csproj" />
    <ProjectReference
      Include="../../src/SparseFragments.Generator/SparseFragments.Generator.csproj"
      OutputItemType="Analyzer"
      ReferenceOutputAssembly="true"
    />
  </ItemGroup>
</Project>
