using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;
using SparseFragments.Generator.Shared;

namespace SparseFragments.Generator;

/// <summary>Generates standalone sparse fragments for <c>[SparseFragmentModel]</c> types.</summary>
[Generator(LanguageNames.CSharp)]
public sealed class SparseFragmentsGenerator : IIncrementalGenerator
{
    private const string ModelAttributeName = "SparseFragments.SparseFragmentModelAttribute";
    private const string MergeAttributeName = "SparseFragments.SparseMergeAttribute";
    private const string MergeStrategyBaseName = "SparseFragments.FragmentMergeStrategy<T>";
    private const string EmitIsExternalInitOption =
        "build_property.SparseFragmentsEmitIsExternalInit";
    private const string IsExternalInitHintName = "SparseFragments.IsExternalInit.g.cs";
    private const string IsExternalInitSource =
        "// <auto-generated />\n"
        + "#nullable enable\n"
        + "namespace System.Runtime.CompilerServices\n"
        + "{\n"
        + "    internal static partial class IsExternalInit\n"
        + "    {\n"
        + "    }\n"
        + "}\n";

    private static readonly SparseGeneratorConfig Configuration = new(
        ModelAttributeName,
        MergeAttributeName,
        MergeStrategyBaseName,
        "SparseFragments.SparseCloneReferenceSafeAttribute"
    );

    private static readonly DiagnosticDescriptor MustBePartial = new(
        SparseDiagnosticIds.MustBePartial,
        "Sparse fragment model must be partial",
        "Model '{0}' must be declared partial",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf001-sparse-fragment-model-must-be-partial"
    );
    private static readonly DiagnosticDescriptor UnsupportedModel = new(
        SparseDiagnosticIds.UnsupportedModel,
        "Unsupported sparse fragment model",
        "Model '{0}' must be a top-level, non-generic, non-abstract class or struct",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf002-unsupported-sparse-fragment-model"
    );
    private static readonly DiagnosticDescriptor MissingConstructor = new(
        SparseDiagnosticIds.MissingConstructor,
        "Model needs a supported constructor",
        "Class model '{0}' must have a parameterless constructor or a constructor whose parameters match public readable properties by name and type; a setter, when present, must be public",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf003-model-needs-a-supported-constructor"
    );
    private static readonly DiagnosticDescriptor InvalidMergeStrategy = new(
        SparseDiagnosticIds.InvalidMergeStrategy,
        "Invalid custom merge strategy",
        "Merge strategy for member '{0}' must derive from FragmentMergeStrategy<TMember> and be a concrete, accessible type",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf004-invalid-custom-merge-strategy"
    );
    private static readonly DiagnosticDescriptor UnsupportedMerge = new(
        SparseDiagnosticIds.UnsupportedMerge,
        "Unsupported merge mode",
        "The configured merge mode is not supported for member '{0}'",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf005-unsupported-merge-mode"
    );
    private static readonly DiagnosticDescriptor UnsupportedStructural = new(
        SparseDiagnosticIds.UnsupportedStructural,
        "Unsupported structural member construction",
        "Member '{0}' has an unsupported structural type; provide a supported public constructor and properties, decorate it as a fragment model, or explicitly select MergeMode.Replace",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf007-unsupported-structural-member-construction"
    );
    private static readonly DiagnosticDescriptor UnsupportedClone = new(
        SparseDiagnosticIds.UnsupportedClone,
        "Unsupported deep clone member",
        "Member '{0}' has a reference shape that cannot be deeply cloned safely (unsupported type or constructor-bound cycle); use a supported structural type or collection, or explicitly mark a reference-safe property with SparseCloneReferenceSafe",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf008-unsupported-deep-clone-member"
    );

    private static readonly DiagnosticDescriptor GeneratedNameCollision = new(
        SparseDiagnosticIds.GeneratedNameCollision,
        "Member conflicts with generated JSON Patch API",
        "Member '{0}' conflicts with a name reserved by the generated JSON Patch API",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf009-member-conflicts-with-generated-json-patch-api"
    );

    private static readonly DiagnosticDescriptor UnsupportedRequired = new(
        SparseDiagnosticIds.UnsupportedRequired,
        "Required member cannot be constructed",
        "Required member '{0}' must be represented by an accessible public property in the fragment construction plan",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf006-required-member-cannot-be-constructed"
    );

    private static readonly DiagnosticDescriptor IncompatiblePromotedModel = new(
        SparseDiagnosticIds.IncompatiblePromotedModel,
        "Incompatible promoted fragment model",
        "Promoted model '{0}' requires incompatible generated semantics from different roots",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf010-incompatible-promoted-fragment-model"
    );

    private static readonly DiagnosticDescriptor UnkeyedStructuralSequence = new(
        SparseDiagnosticIds.UnkeyedStructuralSequence,
        "Structural sequence without usable key",
        "Member '{0}' is a structural sequence without a usable key; declare exactly one key on the element type (one [SparseKey] property, one type-level [SparseKey(nameof(...), ...)] composite, or one ISparseKeyed<TKey> implementation), or explicitly select MergeMode.Append, MergeMode.SetUnion, or a custom merge strategy",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf011-structural-sequence-without-usable-key"
    );

    private static readonly DiagnosticDescriptor ConflictingKeyMechanisms = new(
        SparseDiagnosticIds.ConflictingKeyMechanisms,
        "Conflicting SparseKey mechanisms",
        "Type '{0}' declares more than one SparseKey mechanism; exactly one key definition may apply (one [SparseKey] property, one type-level [SparseKey(nameof(...), ...)], or one ISparseKeyed<TKey> implementation) and there is no precedence between them",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf012-conflicting-sparsekey-mechanisms"
    );

    private static readonly DiagnosticDescriptor MultiplePropertyKeys = new(
        SparseDiagnosticIds.MultiplePropertyKeys,
        "Multiple SparseKey properties",
        "Type '{0}' marks more than one property with [SparseKey]; multiple property-level keys are not a composite key, use a single type-level [SparseKey(nameof(...), ...)] declaration instead",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf013-multiple-sparsekey-properties"
    );

    private static readonly DiagnosticDescriptor InvalidKeyAttributeShape = new(
        SparseDiagnosticIds.InvalidKeyAttributeShape,
        "Invalid SparseKey declaration",
        "SparseKey declaration on '{0}' is invalid; property-level [SparseKey] takes no arguments and type-level [SparseKey] requires at least one property name",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf014-invalid-sparsekey-declaration"
    );

    private static readonly DiagnosticDescriptor MissingKeyComponent = new(
        SparseDiagnosticIds.MissingKeyComponent,
        "Missing SparseKey component",
        "Key component '{0}' does not resolve to a property of the model",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf015-missing-sparsekey-component"
    );

    private static readonly DiagnosticDescriptor DuplicateKeyComponent = new(
        SparseDiagnosticIds.DuplicateKeyComponent,
        "Duplicate SparseKey component",
        "Duplicate key component '{0}'; type-level key components must resolve to distinct properties",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf016-duplicate-sparsekey-component"
    );

    private static readonly DiagnosticDescriptor InaccessibleKeyProperty = new(
        SparseDiagnosticIds.InaccessibleKeyProperty,
        "Inaccessible SparseKey property",
        "Key property '{0}' must be a publicly readable instance property; static, indexer, or non-publicly-readable properties cannot serve as stable identity",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf017-inaccessible-sparsekey-property"
    );

    private static readonly DiagnosticDescriptor NullableKey = new(
        SparseDiagnosticIds.NullableKey,
        "Nullable SparseKey",
        "Key '{0}' must not be nullable; nullable key values/types are not supported for keyed collection identity",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf018-nullable-sparsekey"
    );

    private static readonly DiagnosticDescriptor UnsupportedKeyShape = new(
        SparseDiagnosticIds.UnsupportedKeyShape,
        "Unsupported SparseKey shape",
        "Key '{0}' has a collection-shaped type; collection-shaped keys/components are not supported for keyed collection identity",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf019-unsupported-sparsekey-shape"
    );

    private static readonly DiagnosticDescriptor InvalidKeyedInterface = new(
        SparseDiagnosticIds.InvalidKeyedInterface,
        "Invalid ISparseKeyed implementation",
        "Type '{0}' has an invalid or ambiguous ISparseKeyed<TKey> implementation; implement exactly one ISparseKeyed<TKey> with a publicly readable instance SparseKey property and a non-nullable, non-collection key type",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf020-invalid-isparsekeyed-implementation"
    );

    private static readonly DiagnosticDescriptor DuplicateJsonPropertyName = new(
        SparseDiagnosticIds.DuplicateJsonPropertyName,
        "Duplicate JSON property name",
        "Multiple members map to the same JSON property name '{0}'",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf021-duplicate-json-property-name"
    );

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var analyzed = context
            .SyntaxProvider.ForAttributeWithMetadataName(
                ModelAttributeName,
                static (node, _) => node is TypeDeclarationSyntax,
                static (attributeContext, cancellationToken) =>
                    SparseModelAnalyzer.Analyze(
                        (INamedTypeSymbol)attributeContext.TargetSymbol,
                        Configuration,
                        cancellationToken
                    )
            )
            .WithTrackingName("SparseFragmentsGenerator.Analysis");
        var bclSetSupport = context
            .CompilationProvider.Select(
                static (compilation, _) =>
                    (
                        ReadOnlySet: SparseCollectionAnalyzer.HashSetImplementsReadOnlySet(
                            compilation
                        ),
                        Capacity: SparseCollectionAnalyzer.HashSetSupportsCapacity(compilation)
                    )
            )
            .WithComparer(EqualityComparer<(bool ReadOnlySet, bool Capacity)>.Default)
            .WithTrackingName("SparseFragmentsGenerator.BclSetSupport");
        var generated = analyzed
            .Combine(bclSetSupport)
            .Select(
                static (input, cancellationToken) =>
                    Render(
                        input.Left,
                        input.Right.ReadOnlySet,
                        input.Right.Capacity,
                        cancellationToken
                    )
            )
            .WithTrackingName("SparseFragmentsGenerator.Output");

        context.RegisterSourceOutput(
            generated,
            static (productionContext, result) => Emit(productionContext, result)
        );

        var promotedPerRoot = analyzed
            .Select(static (analysis, _) => analysis.PromotedModels)
            .WithTrackingName("SparseFragmentsGenerator.PromotedPerRoot");
        var promotedContributions = promotedPerRoot
            .SelectMany(
                static (models, _) =>
                    models.IsDefault ? ImmutableArray<SparsePromotedModel>.Empty : models
            )
            .WithTrackingName("SparseFragmentsGenerator.PromotedContributions");
        var explicitRootNames = analyzed
            .Select(static (analysis, _) => analysis.Model?.ModelTypeName)
            .Where(static name => name is not null)
            .Select(static (name, _) => name!)
            .WithTrackingName("SparseFragmentsGenerator.ExplicitRoots")
            .Collect();
        var promotedDedup = promotedContributions
            .Collect()
            .Combine(explicitRootNames)
            .Select(
                static (input, cancellationToken) =>
                    SparsePromotedAggregation.Deduplicate(
                        input.Left,
                        input.Right,
                        cancellationToken
                    )
            )
            .WithTrackingName("SparseFragmentsGenerator.PromotedDedup");
        var distinctPromoted = promotedDedup
            .SelectMany(static (result, _) => result.Distinct)
            .WithTrackingName("SparseFragmentsGenerator.PromotedDistinct");
        var promotedSources = distinctPromoted
            .Combine(bclSetSupport)
            .Select(
                static (input, cancellationToken) =>
                    RenderSinglePromoted(
                        input.Left,
                        input.Right.ReadOnlySet,
                        input.Right.Capacity,
                        cancellationToken
                    )
            )
            .WithTrackingName("SparseFragmentsGenerator.Promoted");
        context.RegisterSourceOutput(
            promotedSources,
            static (productionContext, result) => Emit(productionContext, result)
        );
        var promotedConflicts = promotedDedup
            .SelectMany(static (result, _) => result.Incompatible)
            .Select(
                static (entry, _) =>
                    new SparseGenerationResult(
                        null,
                        null,
                        ImmutableArray.Create(
                            new SparseGeneratorDiagnostic(
                                SparseDiagnosticIds.IncompatiblePromotedModel,
                                null,
                                entry.DisplayName
                            )
                        )
                    )
            )
            .WithTrackingName("SparseFragmentsGenerator.PromotedConflicts");
        context.RegisterSourceOutput(
            promotedConflicts,
            static (productionContext, result) => Emit(productionContext, result)
        );

        var hasModels = analyzed
            .Select(static (analysis, _) => analysis.Model.HasValue)
            .Collect()
            .Select(static (presence, _) => presence.Any(static value => value))
            .WithComparer(EqualityComparer<bool>.Default);
        var shouldEmitIsExternalInit = context
            .CompilationProvider.Combine(context.AnalyzerConfigOptionsProvider)
            .Combine(hasModels)
            .Select(
                static (input, _) =>
                {
                    var ((compilation, options), anyModels) = input;
                    return anyModels
                        && ShouldEmitIsExternalInit(
                            compilation,
                            IsExternalInitEmissionEnabled(options)
                        );
                }
            )
            .WithComparer(EqualityComparer<bool>.Default)
            .WithTrackingName("SparseFragmentsGenerator.IsExternalInit");
        context.RegisterSourceOutput(
            shouldEmitIsExternalInit,
            static (productionContext, emit) =>
            {
                if (emit)
                    productionContext.AddSource(
                        IsExternalInitHintName,
                        SourceText.From(IsExternalInitSource, Encoding.UTF8)
                    );
            }
        );
    }

    private static bool IsExternalInitEmissionEnabled(AnalyzerConfigOptionsProvider options) =>
        !options.GlobalOptions.TryGetValue(EmitIsExternalInitOption, out var value)
        || !string.Equals(value, "false", StringComparison.OrdinalIgnoreCase);

    private static bool ShouldEmitIsExternalInit(Compilation compilation, bool configured) =>
        SparseExternalInit.ShouldEmitIsExternalInit(compilation, configured);

    private static void Emit(SourceProductionContext context, SparseGenerationResult result)
    {
        context.CancellationToken.ThrowIfCancellationRequested();
        foreach (var diagnostic in result.Diagnostics)
        {
            context.CancellationToken.ThrowIfCancellationRequested();
            context.ReportDiagnostic(
                diagnostic.Arguments.Length <= 1
                    ? Diagnostic.Create(
                        GetDescriptor(diagnostic.DescriptorId),
                        diagnostic.Location ?? Location.None,
                        diagnostic.Argument1
                    )
                    : Diagnostic.Create(
                        GetDescriptor(diagnostic.DescriptorId),
                        diagnostic.Location ?? Location.None,
                        diagnostic.Arguments.ToArray()
                    )
            );
        }

        if (result.HintName is not null && result.Source is not null)
        {
            context.AddSource(result.HintName, SourceText.From(result.Source, Encoding.UTF8));
        }
    }

    private static SparseGenerationResult Render(
        SparseGenerationAnalysis analysis,
        bool bclHashSetImplementsReadOnlySet,
        bool bclHashSetSupportsCapacity,
        CancellationToken cancellationToken
    )
    {
        cancellationToken.ThrowIfCancellationRequested();
        if (!analysis.Model.HasValue)
        {
            return new SparseGenerationResult(null, null, analysis.Diagnostics);
        }

        var model = analysis.Model.Value;
        var source = SparseFragmentEmitter.BuildSource(
            model,
            analysis.Members,
            analysis.PocoCloneModels,
            analysis.StructuralModels,
            bclHashSetImplementsReadOnlySet,
            bclHashSetSupportsCapacity,
            cancellationToken
        );
        return new SparseGenerationResult(model.HintName, source, analysis.Diagnostics);
    }

    private static DiagnosticDescriptor GetDescriptor(string id) =>
        id switch
        {
            SparseDiagnosticIds.MustBePartial => MustBePartial,
            SparseDiagnosticIds.UnsupportedModel => UnsupportedModel,
            SparseDiagnosticIds.MissingConstructor => MissingConstructor,
            SparseDiagnosticIds.InvalidMergeStrategy => InvalidMergeStrategy,
            SparseDiagnosticIds.UnsupportedMerge => UnsupportedMerge,
            SparseDiagnosticIds.UnsupportedRequired => UnsupportedRequired,
            SparseDiagnosticIds.UnsupportedStructural => UnsupportedStructural,
            SparseDiagnosticIds.UnsupportedClone => UnsupportedClone,
            SparseDiagnosticIds.GeneratedNameCollision => GeneratedNameCollision,
            SparseDiagnosticIds.IncompatiblePromotedModel => IncompatiblePromotedModel,
            SparseDiagnosticIds.UnkeyedStructuralSequence => UnkeyedStructuralSequence,
            SparseDiagnosticIds.ConflictingKeyMechanisms => ConflictingKeyMechanisms,
            SparseDiagnosticIds.MultiplePropertyKeys => MultiplePropertyKeys,
            SparseDiagnosticIds.InvalidKeyAttributeShape => InvalidKeyAttributeShape,
            SparseDiagnosticIds.MissingKeyComponent => MissingKeyComponent,
            SparseDiagnosticIds.DuplicateKeyComponent => DuplicateKeyComponent,
            SparseDiagnosticIds.InaccessibleKeyProperty => InaccessibleKeyProperty,
            SparseDiagnosticIds.NullableKey => NullableKey,
            SparseDiagnosticIds.UnsupportedKeyShape => UnsupportedKeyShape,
            SparseDiagnosticIds.InvalidKeyedInterface => InvalidKeyedInterface,
            SparseDiagnosticIds.DuplicateJsonPropertyName => DuplicateJsonPropertyName,
            _ => throw new global::System.ArgumentOutOfRangeException(nameof(id), id, null),
        };

    private static SparseGenerationResult RenderSinglePromoted(
        SparsePromotedModel promoted,
        bool bclHashSetImplementsReadOnlySet,
        bool bclHashSetSupportsCapacity,
        CancellationToken cancellationToken
    )
    {
        cancellationToken.ThrowIfCancellationRequested();
        // Promoted collisions stay render-time (the promoted path carries no
        // analysis diagnostics) but run on the shared collision primitive.
        var promotedCollision = SparseShapeValidation.FindFirstReservedNameCollision(
            promoted.Members,
            SparseShapeValidation.SparseFragmentsReservedNames
        );
        if (promotedCollision is not null)
        {
            return new SparseGenerationResult(
                null,
                null,
                ImmutableArray.Create(
                    new SparseGeneratorDiagnostic(
                        SparseDiagnosticIds.GeneratedNameCollision,
                        null,
                        promotedCollision
                    )
                )
            );
        }

        var hint = SparseFragmentEmitter.GetPromotedHintName(promoted.Model, cancellationToken);
        var source = SparseFragmentEmitter.BuildPromotedSource(
            promoted,
            bclHashSetImplementsReadOnlySet,
            bclHashSetSupportsCapacity,
            cancellationToken
        );
        return new SparseGenerationResult(
            hint,
            source,
            ImmutableArray<SparseGeneratorDiagnostic>.Empty
        );
    }
}
