using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;
using SparseFragments.Generator.Shared;

namespace SparseFragments.Generator;

/// <summary>Generates standalone sparse fragments for <c>[SparseFragmentModel]</c> types.</summary>
[Generator(LanguageNames.CSharp)]
public sealed class SparseFragmentsGenerator : IIncrementalGenerator
{
    private const string ModelAttributeName = "SparseFragments.SparseFragmentModelAttribute";
    private const string MergeAttributeName = "SparseFragments.SparseMergeAttribute";
    private const string MergeStrategyBaseName = "SparseFragments.FragmentMergeStrategy<T>";
    private const string RebasePolicyAttributeName = "SparseFragments.SparseRebasePolicyAttribute";
    private const string RebasePolicyBaseName = "SparseFragments.FragmentRebasePolicy<T>";

    private const string EmitIsExternalInitOption =
        "build_property.SparseFragmentsEmitIsExternalInit";
    private const string IsExternalInitHintName = "SparseFragments.IsExternalInit.g.cs";
    private const string IsExternalInitSource =
        "// <auto-generated />\n"
        + "#nullable enable\n"
        + "namespace System.Runtime.CompilerServices\n"
        + "{\n"
        + "    internal static partial class IsExternalInit\n"
        + "    {\n"
        + "    }\n"
        + "}\n";
    private const string NotNullWhenHintName = "SparseFragments.NotNullWhenAttribute.g.cs";
    private const string NotNullWhenAttributeName =
        "System.Diagnostics.CodeAnalysis.NotNullWhenAttribute";
    private const string NotNullWhenSource =
        "// <auto-generated />\n"
        + "#nullable enable\n"
        + "namespace System.Diagnostics.CodeAnalysis\n"
        + "{\n"
        + "[global::System.AttributeUsage(global::System.AttributeTargets.Parameter, Inherited = false)]\n"
        + "internal sealed class NotNullWhenAttribute : global::System.Attribute\n"
        + "{\n"
        + "    public NotNullWhenAttribute(bool returnValue) => ReturnValue = returnValue;\n"
        + "    public bool ReturnValue { get; }\n"
        + "}\n"
        + "}\n";

    private static readonly SparseGeneratorConfig Configuration = new(
        ModelAttributeMetadataName: ModelAttributeName,
        IgnoreAttributeMetadataName: "SparseFragments.SparseIgnoreAttribute",
        RedactBeforeAttributeMetadataName: "SparseFragments.SparseRedactBeforeAttribute",
        MergeAttributeMetadataName: MergeAttributeName,
        MergeStrategyBaseMetadataName: MergeStrategyBaseName,
        CloneReferenceSafeAttributeMetadataName: "SparseFragments.SparseCloneReferenceSafeAttribute",
        KeyAttributeMetadataName: "SparseFragments.SparseKeyAttribute",
        KeyedInterfaceMetadataName: "SparseFragments.ISparseKeyed<TKey>",
        KeyPropertyName: "SparseKey",
        MergeModeMap: new SparseMergeModeMap(0, 1, 2, 3, 4, 5),
        DiagnosticIds: new SparseDiagnosticIdMap(
            SparseFragmentsDiagnosticIds.MustBePartial,
            SparseFragmentsDiagnosticIds.UnsupportedModel,
            SparseFragmentsDiagnosticIds.MissingConstructor,
            SparseFragmentsDiagnosticIds.InvalidMergeStrategy,
            SparseFragmentsDiagnosticIds.UnsupportedMerge,
            SparseFragmentsDiagnosticIds.UnsupportedRequired,
            SparseFragmentsDiagnosticIds.UnsupportedStructural,
            SparseFragmentsDiagnosticIds.UnsupportedClone,
            SparseFragmentsDiagnosticIds.GeneratedNameCollision,
            SparseFragmentsDiagnosticIds.IncompatiblePromotedModel,
            SparseFragmentsDiagnosticIds.UnkeyedStructuralSequence,
            SparseFragmentsDiagnosticIds.ConflictingKeyMechanisms,
            SparseFragmentsDiagnosticIds.MultiplePropertyKeys,
            SparseFragmentsDiagnosticIds.InvalidKeyAttributeShape,
            SparseFragmentsDiagnosticIds.MissingKeyComponent,
            SparseFragmentsDiagnosticIds.DuplicateKeyComponent,
            SparseFragmentsDiagnosticIds.InaccessibleKeyProperty,
            SparseFragmentsDiagnosticIds.NullableKey,
            SparseFragmentsDiagnosticIds.UnsupportedKeyShape,
            SparseFragmentsDiagnosticIds.InvalidKeyedInterface,
            SparseFragmentsDiagnosticIds.DuplicateJsonPropertyName,
            SparseFragmentsDiagnosticIds.SparseIgnoreOnKey,
            SparseFragmentsDiagnosticIds.SparseIgnoreUnsupportedProperty,
            SparseFragmentsDiagnosticIds.InvalidRebasePolicy,
            SparseFragmentsDiagnosticIds.InvalidEmissionPlan,
            SparseFragmentsDiagnosticIds.UnknownProductMember,
            SparseFragmentsDiagnosticIds.InvalidComparisonStrategy
        ),
        HintNameSuffix: ".SparseFragments.g.cs",
        PromotedHintNameSuffix: ".SparsePromoted.g.cs",
        StructuralHostPrefix: "__SparseStructural_",
        RuntimeDialect: new SparseRuntimeDialect(
            "global::SparseFragments.",
            "global::SparseFragments.Optional",
            "global::SparseFragments.FragmentMergeStrategy",
            "global::SparseFragments.CompilerServices.SparseFragmentRuntime",
            "global::SparseFragments.CompilerServices.SparseFragmentRuntime",
            "global::SparseFragments.CompilerServices.SparseFragmentRuntime",
            "global::SparseFragments.CompilerServices.SparseFragmentRuntime",
            "__sparse_merge_strategy_",
            "__sparse_rebase_policy_"
        ),
        PatchDialect: new SparseFragmentPatchEmitter.SparsePatchDialect(
            "global::SparseFragments.",
            "__sparse_whole",
            "__SparseMembersEmpty",
            SparseFragmentPatchEmitter.Field,
            static _ => string.Empty,
            "Apply",
            false,
            "global::SparseFragments.CompilerServices.SparseFragmentRuntime",
            "global::SparseFragments.SparseConflict",
            "global::SparseFragments.SparseConflictKind",
            static payload => "global::SparseFragments.RebaseResult<" + payload + ">",
            SparseFragmentPatchEmitter.ChildPatch,
            SparseFragmentPatchEmitter.DefaultChildChangeSet,
            MergeStrategyField: static member => "__sparse_merge_strategy_" + member.Id,
            RebaseOptionsType: "global::SparseFragments.ChangePayloadRebaseOptions",
            RebaseModeType: "global::SparseFragments.SparseRebaseMode",
            RebasePolicyType: "global::SparseFragments.FragmentRebasePolicy",
            RebasePolicyField: static member => "__sparse_rebase_policy_" + member.Id,
            InPlaceWriteUnavailableKindMemberName: "InPlaceWriteUnavailable",
            PayloadImplementationContainerPrefix: "__Internal"
        ),
        RebasePolicyAttributeMetadataName: RebasePolicyAttributeName,
        RebasePolicyBaseMetadataName: RebasePolicyBaseName,
        ComparisonAttributeMetadataName: "SparseFragments.SparseCompareAttribute",
        EditSessionInterfaceMetadataName: "SparseFragments.ISparseEditSession",
        GeneratedImplementationNamespace: "SparseFragments.Generated",
        EditSessionDialect: new SparseEditSessionDialect("SparseFragments.Generated"),
        DescriptorDialect: new SparseDescriptorDialect(
            "global::SparseFragments.Generated.IDescriptor",
            "global::SparseFragments.Generated.IDescriptorSet",
            "global::SparseFragments.Generated.IArrayDescriptor",
            "global::SparseFragments.Generated.IDictDescriptor",
            "global::SparseFragments.Generated.SparseDescriptor",
            "global::SparseFragments.Generated.SparseDescriptorSet",
            "global::SparseFragments.Generated.SparseArrayDescriptor",
            "global::SparseFragments.Generated.SparseArrayDescriptorAccess",
            "global::SparseFragments.Generated.SparseDictionaryDescriptor",
            "global::SparseFragments.Generated.SparseDictionaryDescriptorAccess",
            "global::SparseFragments.Generated.SparseDescriptorValue"
        ),
        ReservedGeneratedNames: ImmutableArray.Create(
            "Fragment",
            "FragmentBuilder",
            "Empty",
            "IsEmpty",
            "Merge",
            "ApplyChanges",
            "Diff",
            "DeepClone",
            "From",
            "ToModel",
            "ToBuilder",
            "Build",
            "Patch",
            "JsonConverter",
            "FragmentJsonConverter",
            "ApplyTo",
            "TryApplyTo",
            "WriteTo",
            "ApplyInPlace",
            "ApplyInPlaceResult",
            "EditSession"
        )
    );

    private static readonly DiagnosticDescriptor MustBePartial = new(
        SparseFragmentsDiagnosticIds.MustBePartial,
        "Sparse fragment model must be partial",
        "Model '{0}' must be declared partial",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf001-sparse-fragment-model-must-be-partial"
    );
    private static readonly DiagnosticDescriptor UnsupportedModel = new(
        SparseFragmentsDiagnosticIds.UnsupportedModel,
        "Unsupported sparse fragment model",
        "Model '{0}' must be a top-level, non-generic, non-abstract class or struct",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf002-unsupported-sparse-fragment-model"
    );
    private static readonly DiagnosticDescriptor MissingConstructor = new(
        SparseFragmentsDiagnosticIds.MissingConstructor,
        "Model needs a supported constructor",
        "Class model '{0}' must have a parameterless constructor or a constructor whose parameters match public readable properties by name and type; a setter, when present, must be public",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf003-model-needs-a-supported-constructor"
    );
    private static readonly DiagnosticDescriptor InvalidMergeStrategy = new(
        SparseFragmentsDiagnosticIds.InvalidMergeStrategy,
        "Invalid custom merge strategy",
        "Merge strategy for member '{0}' must derive from FragmentMergeStrategy<TMember> and be a concrete, accessible type",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf004-invalid-custom-merge-strategy"
    );
    private static readonly DiagnosticDescriptor InvalidRebasePolicy = new(
        SparseFragmentsDiagnosticIds.InvalidRebasePolicy,
        "Invalid custom rebase policy",
        "Rebase policy for member '{0}' must derive from FragmentRebasePolicy<TMember>, be a concrete, accessible type, and target a scalar or whole-replace member",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf027-invalid-custom-rebase-policy"
    );
    private static readonly DiagnosticDescriptor InvalidComparisonStrategy = new(
        SparseFragmentsDiagnosticIds.InvalidComparisonStrategy,
        "Invalid equality comparer",
        "Comparison rule for member '{0}' must use a concrete accessible type implementing IEqualityComparer<TMember> with an accessible parameterless constructor",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf030-invalid-comparison-strategy"
    );
    private static readonly DiagnosticDescriptor UnsupportedMerge = new(
        SparseFragmentsDiagnosticIds.UnsupportedMerge,
        "Unsupported merge mode",
        "The configured merge mode is not supported for member '{0}'",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf005-unsupported-merge-mode"
    );
    private static readonly DiagnosticDescriptor UnsupportedStructural = new(
        SparseFragmentsDiagnosticIds.UnsupportedStructural,
        "Unsupported structural member construction",
        "Member '{0}' has an unsupported structural type; provide a supported public constructor and properties, decorate it as a fragment model, or explicitly select MergeMode.Replace",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf007-unsupported-structural-member-construction"
    );
    private static readonly DiagnosticDescriptor UnsupportedClone = new(
        SparseFragmentsDiagnosticIds.UnsupportedClone,
        "Unsupported deep clone member",
        "Member '{0}' has a reference shape that cannot be deeply cloned safely (unsupported type or constructor-bound cycle); use a supported structural type or collection, or explicitly mark a reference-safe property with SparseCloneReferenceSafe",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf008-unsupported-deep-clone-member"
    );

    private static readonly DiagnosticDescriptor GeneratedNameCollision = new(
        SparseFragmentsDiagnosticIds.GeneratedNameCollision,
        "Member conflicts with generated API",
        "Member '{0}' conflicts with a name reserved by the generated API",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf009-member-conflicts-with-generated-api"
    );

    private static readonly DiagnosticDescriptor UnsupportedRequired = new(
        SparseFragmentsDiagnosticIds.UnsupportedRequired,
        "Required member cannot be constructed",
        "Required member '{0}' must be represented by an accessible public property in the fragment construction plan",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf006-required-member-cannot-be-constructed"
    );

    private static readonly DiagnosticDescriptor IncompatiblePromotedModel = new(
        SparseFragmentsDiagnosticIds.IncompatiblePromotedModel,
        "Incompatible promoted fragment model",
        "Promoted model '{0}' requires incompatible generated semantics from different roots",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf010-incompatible-promoted-fragment-model"
    );

    private static readonly DiagnosticDescriptor UnkeyedStructuralSequence = new(
        SparseFragmentsDiagnosticIds.UnkeyedStructuralSequence,
        "Structural sequence without usable key",
        "Member '{0}' is a structural sequence without a usable key; declare exactly one key on the element type (one [SparseKey] property, one type-level [SparseKey(nameof(...), ...)] composite, or one ISparseKeyed<TKey> implementation), or explicitly select MergeMode.Replace, MergeMode.Append, MergeMode.SetUnion, or a custom merge strategy",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf011-structural-sequence-without-usable-key"
    );

    private static readonly DiagnosticDescriptor ConflictingKeyMechanisms = new(
        SparseFragmentsDiagnosticIds.ConflictingKeyMechanisms,
        "Conflicting SparseKey mechanisms",
        "Type '{0}' declares more than one SparseKey mechanism; exactly one key definition may apply (one [SparseKey] property, one type-level [SparseKey(nameof(...), ...)], or one ISparseKeyed<TKey> implementation) and there is no precedence between them",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf012-conflicting-sparsekey-mechanisms"
    );

    private static readonly DiagnosticDescriptor MultiplePropertyKeys = new(
        SparseFragmentsDiagnosticIds.MultiplePropertyKeys,
        "Multiple SparseKey properties",
        "Type '{0}' marks more than one property with [SparseKey]; multiple property-level keys are not a composite key, use a single type-level [SparseKey(nameof(...), ...)] declaration instead",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf013-multiple-sparsekey-properties"
    );

    private static readonly DiagnosticDescriptor InvalidKeyAttributeShape = new(
        SparseFragmentsDiagnosticIds.InvalidKeyAttributeShape,
        "Invalid SparseKey declaration",
        "SparseKey declaration on '{0}' is invalid; property-level [SparseKey] takes no arguments and type-level [SparseKey] requires at least one property name",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf014-invalid-sparsekey-declaration"
    );

    private static readonly DiagnosticDescriptor MissingKeyComponent = new(
        SparseFragmentsDiagnosticIds.MissingKeyComponent,
        "Missing SparseKey component",
        "Key component '{0}' does not resolve to a property of the model",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf015-missing-sparsekey-component"
    );

    private static readonly DiagnosticDescriptor DuplicateKeyComponent = new(
        SparseFragmentsDiagnosticIds.DuplicateKeyComponent,
        "Duplicate SparseKey component",
        "Duplicate key component '{0}'; type-level key components must resolve to distinct properties",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf016-duplicate-sparsekey-component"
    );

    private static readonly DiagnosticDescriptor InaccessibleKeyProperty = new(
        SparseFragmentsDiagnosticIds.InaccessibleKeyProperty,
        "Inaccessible SparseKey property",
        "Key property '{0}' must be a publicly readable instance property; static, indexer, or non-publicly-readable properties cannot serve as stable identity",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf017-inaccessible-sparsekey-property"
    );

    private static readonly DiagnosticDescriptor NullableKey = new(
        SparseFragmentsDiagnosticIds.NullableKey,
        "Nullable SparseKey",
        "Key '{0}' must not be nullable; nullable key values/types are not supported for keyed collection identity",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf018-nullable-sparsekey"
    );

    private static readonly DiagnosticDescriptor UnsupportedKeyShape = new(
        SparseFragmentsDiagnosticIds.UnsupportedKeyShape,
        "Unsupported SparseKey shape",
        "Key '{0}' has a collection-shaped type; collection-shaped keys/components are not supported for keyed collection identity",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf019-unsupported-sparsekey-shape"
    );

    private static readonly DiagnosticDescriptor InvalidKeyedInterface = new(
        SparseFragmentsDiagnosticIds.InvalidKeyedInterface,
        "Invalid ISparseKeyed implementation",
        "Type '{0}' has an invalid or ambiguous ISparseKeyed<TKey> implementation; implement exactly one ISparseKeyed<TKey> with a publicly readable instance SparseKey property and a non-nullable, non-collection key type",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf020-invalid-isparsekeyed-implementation"
    );

    private static readonly DiagnosticDescriptor DuplicateJsonPropertyName = new(
        SparseFragmentsDiagnosticIds.DuplicateJsonPropertyName,
        "Duplicate JSON property name",
        "Multiple members map to the same JSON property name '{0}'",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf021-duplicate-json-property-name"
    );
    private static readonly DiagnosticDescriptor SparseIgnoreOnKey = new(
        SparseFragmentsDiagnosticIds.SparseIgnoreOnKey,
        "SparseIgnore cannot exclude a key",
        "Property '{0}' is a SparseKey or a component of a composite SparseKey and cannot be ignored",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf022-sparseignore-on-key"
    );
    private static readonly DiagnosticDescriptor SparseIgnoreUnsupportedProperty = new(
        SparseFragmentsDiagnosticIds.SparseIgnoreUnsupportedProperty,
        "SparseIgnore property cannot be preserved",
        "Property '{0}' cannot be ignored because required, constructor-bound without a default, or init-only properties cannot be carried through model construction",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf023-sparseignore-on-unsupported-property"
    );
    private static readonly DiagnosticDescriptor InvalidUnassignedKey = new(
        SparseFragmentsDiagnosticIds.InvalidUnassignedKey,
        "Invalid unassigned key sentinel",
        "Invalid unassigned key sentinel: {0}",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf024-invalid-unassigned-key-sentinel"
    );
    private static readonly DiagnosticDescriptor UnsupportedUnassignedKey = new(
        SparseFragmentsDiagnosticIds.UnsupportedUnassignedKey,
        "Unsupported unassigned key sentinel",
        "Unassigned key sentinels are not supported for composite or interface keys on '{0}'",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf025-unsupported-unassigned-key-sentinel"
    );
    private static readonly DiagnosticDescriptor InPlaceWriteUnavailable = new(
        SparseFragmentsDiagnosticIds.InPlaceWriteUnavailable,
        "In-place updates are limited",
        "Model '{0}' has init-only or constructor-only members; patch and try-apply APIs report structured failures when changes include them",
        "SparseFragments",
        DiagnosticSeverity.Info,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf026-in-place-submit-is-unavailable"
    );
    private static readonly DiagnosticDescriptor InvalidEmissionPlan = new(
        SparseFragmentsDiagnosticIds.InvalidEmissionPlan,
        "Invalid downstream emission plan",
        "Invalid emission plan: {0}",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf028-invalid-downstream-emission-plan"
    );
    private static readonly DiagnosticDescriptor UnknownProductMember = new(
        SparseFragmentsDiagnosticIds.UnknownProductMember,
        "Unknown product member",
        "Product policy references unknown member '{0}'",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf029-unknown-product-member"
    );

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var analyzed = context
            .SyntaxProvider.ForAttributeWithMetadataName(
                ModelAttributeName,
                static (node, _) => node is TypeDeclarationSyntax,
                static (attributeContext, cancellationToken) =>
                    SparseModelAnalyzer.Analyze(
                        (INamedTypeSymbol)attributeContext.TargetSymbol,
                        Configuration,
                        cancellationToken
                    )
            )
            .WithTrackingName("SparseFragmentsGenerator.Analysis");
        var bclSetSupport = context
            .CompilationProvider.Select(
                static (compilation, _) =>
                    (
                        ReadOnlySet: SparseCollectionAnalyzer.HashSetImplementsReadOnlySet(
                            compilation
                        ),
                        Capacity: SparseCollectionAnalyzer.HashSetSupportsCapacity(compilation)
                    )
            )
            .WithComparer(EqualityComparer<(bool ReadOnlySet, bool Capacity)>.Default)
            .WithTrackingName("SparseFragmentsGenerator.BclSetSupport");
        var generated = analyzed
            .Combine(bclSetSupport)
            .Select(
                static (input, cancellationToken) =>
                    Render(
                        input.Left,
                        input.Right.ReadOnlySet,
                        input.Right.Capacity,
                        cancellationToken
                    )
            )
            .WithTrackingName("SparseFragmentsGenerator.Output");

        context.RegisterSourceOutput(
            generated,
            static (productionContext, result) => Emit(productionContext, result)
        );

        var promotedPerRoot = analyzed
            .Select(static (analysis, _) => analysis.PromotedModels)
            .WithTrackingName("SparseFragmentsGenerator.PromotedPerRoot");
        var promotedContributions = promotedPerRoot
            .SelectMany(
                static (models, _) =>
                    models.IsDefault ? ImmutableArray<SparsePromotedModel>.Empty : models
            )
            .WithTrackingName("SparseFragmentsGenerator.PromotedContributions");
        var explicitRootNames = analyzed
            .Select(static (analysis, _) => analysis.Model?.ModelTypeName)
            .Where(static name => name is not null)
            .Select(static (name, _) => name!)
            .WithTrackingName("SparseFragmentsGenerator.ExplicitRoots")
            .Collect();
        var promotedDedup = promotedContributions
            .Collect()
            .Combine(explicitRootNames)
            .Select(
                static (input, cancellationToken) =>
                    SparsePromotedAggregation.Deduplicate(
                        input.Left,
                        input.Right,
                        cancellationToken
                    )
            )
            .WithTrackingName("SparseFragmentsGenerator.PromotedDedup");
        var distinctPromoted = promotedDedup
            .SelectMany(static (result, _) => result.Distinct)
            .WithTrackingName("SparseFragmentsGenerator.PromotedDistinct");
        var promotedSources = distinctPromoted
            .Combine(bclSetSupport)
            .Select(
                static (input, cancellationToken) =>
                    RenderSinglePromoted(
                        input.Left,
                        input.Right.ReadOnlySet,
                        input.Right.Capacity,
                        cancellationToken
                    )
            )
            .WithTrackingName("SparseFragmentsGenerator.Promoted");
        context.RegisterSourceOutput(
            promotedSources,
            static (productionContext, result) => Emit(productionContext, result)
        );
        var promotedConflicts = promotedDedup
            .SelectMany(static (result, _) => result.Incompatible)
            .Select(
                static (entry, _) =>
                    new SparseGenerationResult(
                        null,
                        null,
                        ImmutableArray.Create(
                            new SparseGeneratorDiagnostic(
                                SparseFragmentsDiagnosticIds.IncompatiblePromotedModel,
                                null,
                                entry.DisplayName
                            )
                        )
                    )
            )
            .WithTrackingName("SparseFragmentsGenerator.PromotedConflicts");
        context.RegisterSourceOutput(
            promotedConflicts,
            static (productionContext, result) => Emit(productionContext, result)
        );

        var hasModels = analyzed
            .Select(static (analysis, _) => analysis.Model.HasValue)
            .Collect()
            .Select(static (presence, _) => presence.Any(static value => value))
            .WithComparer(EqualityComparer<bool>.Default);
        var hasEditSessionModels = analyzed
            .Select(
                static (analysis, _) => analysis.Model.HasValue && !analysis.Model.Value.IsStruct
            )
            .Collect()
            .Select(static (presence, _) => presence.Any(static value => value))
            .WithComparer(EqualityComparer<bool>.Default);
        context.RegisterSourceOutput(
            hasEditSessionModels,
            static (productionContext, emit) =>
            {
                if (emit)
                    SparseEditSessionEmitter.EmitCore(productionContext, Configuration);
            }
        );
        var shouldEmitIsExternalInit = context
            .CompilationProvider.Combine(context.AnalyzerConfigOptionsProvider)
            .Combine(hasModels)
            .Select(
                static (input, _) =>
                {
                    var ((compilation, options), anyModels) = input;
                    return anyModels
                        && ShouldEmitIsExternalInit(
                            compilation,
                            IsExternalInitEmissionEnabled(options)
                        );
                }
            )
            .WithComparer(EqualityComparer<bool>.Default)
            .WithTrackingName("SparseFragmentsGenerator.IsExternalInit");
        context.RegisterSourceOutput(
            shouldEmitIsExternalInit,
            static (productionContext, emit) =>
            {
                if (emit)
                    productionContext.AddSource(
                        IsExternalInitHintName,
                        SourceText.From(IsExternalInitSource, Encoding.UTF8)
                    );
            }
        );
        var shouldEmitNotNullWhen = context
            .CompilationProvider.Combine(hasModels)
            .Select(
                static (input, _) =>
                    input.Right
                    && input.Left.GetTypeByMetadataName(NotNullWhenAttributeName) is null
            )
            .WithComparer(EqualityComparer<bool>.Default)
            .WithTrackingName("SparseFragmentsGenerator.NotNullWhen");
        context.RegisterSourceOutput(
            shouldEmitNotNullWhen,
            static (productionContext, emit) =>
            {
                if (emit)
                    productionContext.AddSource(
                        NotNullWhenHintName,
                        SourceText.From(NotNullWhenSource, Encoding.UTF8)
                    );
            }
        );
    }

    private static bool IsExternalInitEmissionEnabled(AnalyzerConfigOptionsProvider options) =>
        !options.GlobalOptions.TryGetValue(EmitIsExternalInitOption, out var value)
        || !string.Equals(value, "false", StringComparison.OrdinalIgnoreCase);

    private static bool ShouldEmitIsExternalInit(Compilation compilation, bool configured) =>
        SparseExternalInit.ShouldEmitIsExternalInit(compilation, configured);

    private static void Emit(SourceProductionContext context, SparseGenerationResult result)
    {
        context.CancellationToken.ThrowIfCancellationRequested();
        foreach (var diagnostic in result.Diagnostics)
        {
            context.CancellationToken.ThrowIfCancellationRequested();
            context.ReportDiagnostic(
                diagnostic.Arguments.Length <= 1
                    ? Diagnostic.Create(
                        GetDescriptor(diagnostic.DescriptorId),
                        diagnostic.Location ?? Location.None,
                        diagnostic.Argument1
                    )
                    : Diagnostic.Create(
                        GetDescriptor(diagnostic.DescriptorId),
                        diagnostic.Location ?? Location.None,
                        diagnostic.Arguments.ToArray()
                    )
            );
        }

        if (result.HintName is not null && result.Source is not null)
        {
            context.AddSource(result.HintName, SourceText.From(result.Source, Encoding.UTF8));
        }

        // Model-facing surface and implementation files share one result so
        // per-model incremental isolation covers both with stable hint names.
        // A default (not merely empty) additional-sources array must not be
        // enumerated: ImmutableArray iteration over default throws.
        if (!result.AdditionalSources.IsDefaultOrEmpty)
        {
            foreach (var additional in result.AdditionalSources)
            {
                context.CancellationToken.ThrowIfCancellationRequested();
                context.AddSource(
                    additional.HintName,
                    SourceText.From(additional.Source, Encoding.UTF8)
                );
            }
        }
    }

    private static SparseGenerationResult Render(
        SparseGenerationAnalysis analysis,
        bool bclHashSetImplementsReadOnlySet,
        bool bclHashSetSupportsCapacity,
        CancellationToken cancellationToken
    )
    {
        cancellationToken.ThrowIfCancellationRequested();
        if (!analysis.Model.HasValue)
        {
            return new SparseGenerationResult(null, null, analysis.Diagnostics);
        }

        var model = analysis.Model.Value;
        var source = SparseFragmentEmitter.BuildSource(
            model,
            analysis.Members,
            analysis.PocoCloneModels,
            analysis.ReadOnlyViewModels,
            analysis.StructuralModels,
            bclHashSetImplementsReadOnlySet,
            bclHashSetSupportsCapacity,
            cancellationToken,
            Configuration,
            (code, generatedModel, members) =>
                SparseModelExtensionsEmitter.Append(code, generatedModel, members, Configuration)
        );
        return new SparseGenerationResult(model.HintName, source, analysis.Diagnostics);
    }

    private static DiagnosticDescriptor GetDescriptor(string id) =>
        id switch
        {
            SparseFragmentsDiagnosticIds.MustBePartial => MustBePartial,
            SparseFragmentsDiagnosticIds.UnsupportedModel => UnsupportedModel,
            SparseFragmentsDiagnosticIds.MissingConstructor => MissingConstructor,
            SparseFragmentsDiagnosticIds.InvalidMergeStrategy => InvalidMergeStrategy,
            SparseFragmentsDiagnosticIds.InvalidRebasePolicy => InvalidRebasePolicy,
            SparseFragmentsDiagnosticIds.InvalidComparisonStrategy => InvalidComparisonStrategy,
            SparseFragmentsDiagnosticIds.UnsupportedMerge => UnsupportedMerge,
            SparseFragmentsDiagnosticIds.UnsupportedRequired => UnsupportedRequired,
            SparseFragmentsDiagnosticIds.UnsupportedStructural => UnsupportedStructural,
            SparseFragmentsDiagnosticIds.UnsupportedClone => UnsupportedClone,
            SparseFragmentsDiagnosticIds.GeneratedNameCollision => GeneratedNameCollision,
            SparseFragmentsDiagnosticIds.IncompatiblePromotedModel => IncompatiblePromotedModel,
            SparseFragmentsDiagnosticIds.UnkeyedStructuralSequence => UnkeyedStructuralSequence,
            SparseFragmentsDiagnosticIds.ConflictingKeyMechanisms => ConflictingKeyMechanisms,
            SparseFragmentsDiagnosticIds.MultiplePropertyKeys => MultiplePropertyKeys,
            SparseFragmentsDiagnosticIds.InvalidKeyAttributeShape => InvalidKeyAttributeShape,
            SparseFragmentsDiagnosticIds.MissingKeyComponent => MissingKeyComponent,
            SparseFragmentsDiagnosticIds.DuplicateKeyComponent => DuplicateKeyComponent,
            SparseFragmentsDiagnosticIds.InaccessibleKeyProperty => InaccessibleKeyProperty,
            SparseFragmentsDiagnosticIds.NullableKey => NullableKey,
            SparseFragmentsDiagnosticIds.UnsupportedKeyShape => UnsupportedKeyShape,
            SparseFragmentsDiagnosticIds.InvalidKeyedInterface => InvalidKeyedInterface,
            SparseFragmentsDiagnosticIds.DuplicateJsonPropertyName => DuplicateJsonPropertyName,
            SparseFragmentsDiagnosticIds.SparseIgnoreOnKey => SparseIgnoreOnKey,
            SparseFragmentsDiagnosticIds.SparseIgnoreUnsupportedProperty =>
                SparseIgnoreUnsupportedProperty,
            SparseFragmentsDiagnosticIds.InvalidUnassignedKey => InvalidUnassignedKey,
            SparseFragmentsDiagnosticIds.UnsupportedUnassignedKey => UnsupportedUnassignedKey,
            SparseFragmentsDiagnosticIds.InPlaceWriteUnavailable => InPlaceWriteUnavailable,
            SparseFragmentsDiagnosticIds.InvalidEmissionPlan => InvalidEmissionPlan,
            SparseFragmentsDiagnosticIds.UnknownProductMember => UnknownProductMember,
            _ => throw new global::System.ArgumentOutOfRangeException(nameof(id), id, null),
        };

    private static SparseGenerationResult RenderSinglePromoted(
        SparsePromotedModel promoted,
        bool bclHashSetImplementsReadOnlySet,
        bool bclHashSetSupportsCapacity,
        CancellationToken cancellationToken
    )
    {
        cancellationToken.ThrowIfCancellationRequested();
        // Promoted collisions stay render-time (the promoted path carries no
        // analysis diagnostics) but run on the shared collision primitive.
        var promotedCollision = SparseShapeValidation.FindFirstReservedNameCollision(
            promoted.Members,
            Configuration.EffectiveReservedGeneratedNames
        );
        if (promotedCollision is not null)
        {
            return new SparseGenerationResult(
                null,
                null,
                ImmutableArray.Create(
                    new SparseGeneratorDiagnostic(
                        Configuration.EffectiveDiagnosticIds.GeneratedNameCollision,
                        null,
                        promotedCollision
                    )
                )
            );
        }

        var hint = SparseFragmentEmitter.GetPromotedHintName(
            promoted.Model,
            Configuration.PromotedHintNameSuffix,
            cancellationToken
        );
        var source = SparseFragmentEmitter.BuildPromotedSource(
            promoted,
            bclHashSetImplementsReadOnlySet,
            bclHashSetSupportsCapacity,
            cancellationToken,
            Configuration
        );
        return new SparseGenerationResult(
            hint,
            source,
            ImmutableArray<SparseGeneratorDiagnostic>.Empty
        );
    }
}
