using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;
using SparseFragments.Generator.Shared;

namespace SparseFragments.Generator;

/// <summary>Generates standalone sparse fragments for <c>[SparseFragmentModel]</c> types.</summary>
[Generator(LanguageNames.CSharp)]
public sealed class SparseFragmentsGenerator : IIncrementalGenerator
{
    private const string ModelAttributeName = "SparseFragments.SparseFragmentModelAttribute";
    private const string MergeAttributeName = "SparseFragments.SparseMergeAttribute";
    private const string MergeStrategyBaseName = "SparseFragments.FragmentMergeStrategy<T>";
    private const string IsExternalInitMetadataName =
        "System.Runtime.CompilerServices.IsExternalInit";
    private const string EmitIsExternalInitOption =
        "build_property.SparseFragmentsEmitIsExternalInit";
    private const string IsExternalInitHintName = "SparseFragments.IsExternalInit.g.cs";
    private const string IsExternalInitSource =
        "// <auto-generated />\n"
        + "#nullable enable\n"
        + "namespace System.Runtime.CompilerServices\n"
        + "{\n"
        + "    internal static partial class IsExternalInit\n"
        + "    {\n"
        + "    }\n"
        + "}\n";

    private static readonly SparseGeneratorConfig Configuration = new(
        ModelAttributeName,
        MergeAttributeName,
        MergeStrategyBaseName,
        "SparseFragments.SparseCloneReferenceSafeAttribute"
    );

    private static readonly DiagnosticDescriptor MustBePartial = new(
        SparseDiagnosticIds.MustBePartial,
        "Sparse fragment model must be partial",
        "Model '{0}' must be declared partial",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf001-sparse-fragment-model-must-be-partial"
    );
    private static readonly DiagnosticDescriptor UnsupportedModel = new(
        SparseDiagnosticIds.UnsupportedModel,
        "Unsupported sparse fragment model",
        "Model '{0}' must be a top-level, non-generic, non-abstract class or struct",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf002-unsupported-sparse-fragment-model"
    );
    private static readonly DiagnosticDescriptor MissingConstructor = new(
        SparseDiagnosticIds.MissingConstructor,
        "Model needs a supported constructor",
        "Class model '{0}' must have a parameterless constructor or a constructor whose parameters match public readable properties by name and type; a setter, when present, must be public",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf003-model-needs-a-supported-constructor"
    );
    private static readonly DiagnosticDescriptor InvalidMergeStrategy = new(
        SparseDiagnosticIds.InvalidMergeStrategy,
        "Invalid custom merge strategy",
        "Merge strategy for member '{0}' must derive from FragmentMergeStrategy<TMember> and be a concrete, accessible type",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf004-invalid-custom-merge-strategy"
    );
    private static readonly DiagnosticDescriptor UnsupportedMerge = new(
        SparseDiagnosticIds.UnsupportedMerge,
        "Unsupported merge mode",
        "The configured merge mode is not supported for member '{0}'",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf005-unsupported-merge-mode"
    );
    private static readonly DiagnosticDescriptor UnsupportedStructural = new(
        SparseDiagnosticIds.UnsupportedStructural,
        "Unsupported structural member construction",
        "Member '{0}' has an unsupported structural type; provide a supported public constructor and properties, decorate it as a fragment model, or explicitly select MergeMode.Replace",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf007-unsupported-structural-member-construction"
    );
    private static readonly DiagnosticDescriptor UnsupportedClone = new(
        SparseDiagnosticIds.UnsupportedClone,
        "Unsupported deep clone member",
        "Member '{0}' has a reference shape that cannot be deeply cloned safely (unsupported type or constructor-bound cycle); use a supported structural type or collection, or explicitly mark a reference-safe property with SparseCloneReferenceSafe",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf008-unsupported-deep-clone-member"
    );

    private static readonly DiagnosticDescriptor GeneratedNameCollision = new(
        SparseDiagnosticIds.GeneratedNameCollision,
        "Member conflicts with generated JSON Patch API",
        "Member '{0}' conflicts with a name reserved by the generated JSON Patch API",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf009-member-conflicts-with-generated-json-patch-api"
    );

    private static readonly DiagnosticDescriptor UnsupportedRequired = new(
        SparseDiagnosticIds.UnsupportedRequired,
        "Required member cannot be constructed",
        "Required member '{0}' must be represented by an accessible public property in the fragment construction plan",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf006-required-member-cannot-be-constructed"
    );

    private static readonly DiagnosticDescriptor IncompatiblePromotedModel = new(
        SparseDiagnosticIds.IncompatiblePromotedModel,
        "Incompatible promoted fragment model",
        "Promoted model '{0}' requires incompatible generated semantics from different roots",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf010-incompatible-promoted-fragment-model"
    );

    private static readonly DiagnosticDescriptor UnkeyedStructuralSequence = new(
        SparseDiagnosticIds.UnkeyedStructuralSequence,
        "Structural sequence without usable key",
        "Member '{0}' is a structural sequence without a usable key; add [SparseKey] to the element type, or explicitly select MergeMode.Append, MergeMode.SetUnion, or a custom merge strategy",
        "SparseFragments",
        DiagnosticSeverity.Error,
        true,
        helpLinkUri: "https://github.com/arika0093/SparseFragments/blob/main/docs/analyzer.md#spf011-structural-sequence-without-usable-key"
    );

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var analyzed = context
            .SyntaxProvider.ForAttributeWithMetadataName(
                ModelAttributeName,
                static (node, _) => node is TypeDeclarationSyntax,
                static (attributeContext, cancellationToken) =>
                    SparseModelAnalyzer.Analyze(
                        (INamedTypeSymbol)attributeContext.TargetSymbol,
                        Configuration,
                        cancellationToken
                    )
            )
            .WithTrackingName("SparseFragmentsGenerator.Analysis");
        var bclSetSupport = context
            .CompilationProvider.Select(
                static (compilation, _) =>
                    (
                        ReadOnlySet: SparseCollectionAnalyzer.HashSetImplementsReadOnlySet(
                            compilation
                        ),
                        Capacity: SparseCollectionAnalyzer.HashSetSupportsCapacity(compilation)
                    )
            )
            .WithComparer(EqualityComparer<(bool ReadOnlySet, bool Capacity)>.Default)
            .WithTrackingName("SparseFragmentsGenerator.BclSetSupport");
        var generated = analyzed
            .Combine(bclSetSupport)
            .Select(
                static (input, cancellationToken) =>
                    Render(
                        input.Left,
                        input.Right.ReadOnlySet,
                        input.Right.Capacity,
                        cancellationToken
                    )
            )
            .WithTrackingName("SparseFragmentsGenerator.Output");

        context.RegisterSourceOutput(
            generated,
            static (productionContext, result) => Emit(productionContext, result)
        );

        var promoted = analyzed
            .Collect()
            .Combine(bclSetSupport)
            .Select(
                static (input, cancellationToken) =>
                    RenderPromoted(
                        input.Left,
                        input.Right.ReadOnlySet,
                        input.Right.Capacity,
                        cancellationToken
                    )
            )
            .WithTrackingName("SparseFragmentsGenerator.Promoted");
        context.RegisterSourceOutput(
            promoted,
            static (productionContext, results) =>
            {
                foreach (var result in results)
                {
                    Emit(productionContext, result);
                }
            }
        );

        var hasModels = analyzed
            .Select(static (analysis, _) => analysis.Model.HasValue)
            .Collect()
            .Select(static (presence, _) => presence.Any(static value => value))
            .WithComparer(EqualityComparer<bool>.Default);
        var shouldEmitIsExternalInit = context
            .CompilationProvider.Combine(context.AnalyzerConfigOptionsProvider)
            .Combine(hasModels)
            .Select(
                static (input, _) =>
                {
                    var ((compilation, options), anyModels) = input;
                    return anyModels
                        && ShouldEmitIsExternalInit(
                            compilation,
                            IsExternalInitEmissionEnabled(options)
                        );
                }
            )
            .WithComparer(EqualityComparer<bool>.Default)
            .WithTrackingName("SparseFragmentsGenerator.IsExternalInit");
        context.RegisterSourceOutput(
            shouldEmitIsExternalInit,
            static (productionContext, emit) =>
            {
                if (emit)
                    productionContext.AddSource(
                        IsExternalInitHintName,
                        SourceText.From(IsExternalInitSource, Encoding.UTF8)
                    );
            }
        );
    }

    private static bool IsExternalInitEmissionEnabled(AnalyzerConfigOptionsProvider options) =>
        !options.GlobalOptions.TryGetValue(EmitIsExternalInitOption, out var value)
        || !string.Equals(value, "false", StringComparison.OrdinalIgnoreCase);

    private static bool ShouldEmitIsExternalInit(Compilation compilation, bool configured)
    {
        if (!configured)
            return false;
        var marker = compilation.GetTypeByMetadataName(IsExternalInitMetadataName);
        if (marker is null)
            return true;
        if (SymbolEqualityComparer.Default.Equals(marker.ContainingAssembly, compilation.Assembly))
            return false;
        return marker.DeclaredAccessibility != Accessibility.Public;
    }

    private static void Emit(SourceProductionContext context, SparseGenerationResult result)
    {
        context.CancellationToken.ThrowIfCancellationRequested();
        foreach (var diagnostic in result.Diagnostics)
        {
            context.CancellationToken.ThrowIfCancellationRequested();
            context.ReportDiagnostic(
                Diagnostic.Create(
                    GetDescriptor(diagnostic.DescriptorId),
                    diagnostic.Location ?? Location.None,
                    diagnostic.Argument1
                )
            );
        }

        if (result.HintName is not null && result.Source is not null)
        {
            context.AddSource(result.HintName, SourceText.From(result.Source, Encoding.UTF8));
        }
    }

    private static SparseGenerationResult Render(
        SparseGenerationAnalysis analysis,
        bool bclHashSetImplementsReadOnlySet,
        bool bclHashSetSupportsCapacity,
        CancellationToken cancellationToken
    )
    {
        cancellationToken.ThrowIfCancellationRequested();
        if (!analysis.Model.HasValue)
        {
            return new SparseGenerationResult(null, null, analysis.Diagnostics);
        }

        if (
            analysis.Members.Any(static member =>
                member.Property.Name is "JsonConverter" or "FragmentJsonConverter"
            )
        )
        {
            var colliding = analysis.Members.First(member =>
                member.Property.Name is "JsonConverter" or "FragmentJsonConverter"
            );
            return new SparseGenerationResult(
                null,
                null,
                analysis.Diagnostics.Add(
                    new SparseGeneratorDiagnostic(
                        SparseDiagnosticIds.GeneratedNameCollision,
                        null,
                        colliding.Property.Name
                    )
                )
            );
        }

        var model = analysis.Model.Value;
        var source = SparseFragmentEmitter.BuildSource(
            model,
            analysis.Members,
            analysis.PocoCloneModels,
            analysis.StructuralModels,
            bclHashSetImplementsReadOnlySet,
            bclHashSetSupportsCapacity,
            cancellationToken
        );
        return new SparseGenerationResult(model.HintName, source, analysis.Diagnostics);
    }

    private static DiagnosticDescriptor GetDescriptor(string id) =>
        id switch
        {
            SparseDiagnosticIds.MustBePartial => MustBePartial,
            SparseDiagnosticIds.UnsupportedModel => UnsupportedModel,
            SparseDiagnosticIds.MissingConstructor => MissingConstructor,
            SparseDiagnosticIds.InvalidMergeStrategy => InvalidMergeStrategy,
            SparseDiagnosticIds.UnsupportedMerge => UnsupportedMerge,
            SparseDiagnosticIds.UnsupportedRequired => UnsupportedRequired,
            SparseDiagnosticIds.UnsupportedStructural => UnsupportedStructural,
            SparseDiagnosticIds.UnsupportedClone => UnsupportedClone,
            SparseDiagnosticIds.GeneratedNameCollision => GeneratedNameCollision,
            SparseDiagnosticIds.IncompatiblePromotedModel => IncompatiblePromotedModel,
            SparseDiagnosticIds.UnkeyedStructuralSequence => UnkeyedStructuralSequence,
            _ => throw new global::System.ArgumentOutOfRangeException(nameof(id), id, null),
        };

    private static ImmutableArray<SparseGenerationResult> RenderPromoted(
        ImmutableArray<SparseGenerationAnalysis> analyses,
        bool bclHashSetImplementsReadOnlySet,
        bool bclHashSetSupportsCapacity,
        CancellationToken cancellationToken
    )
    {
        var explicitRoots = new System.Collections.Generic.HashSet<string>(
            analyses
                .Where(static analysis => analysis.Model.HasValue)
                .Select(static analysis => analysis.Model!.Value.ModelTypeName),
            StringComparer.Ordinal
        );

        var deduped = new System.Collections.Generic.SortedDictionary<string, SparsePromotedModel>(
            StringComparer.Ordinal
        );
        var diagnostics = ImmutableArray.CreateBuilder<SparseGenerationResult>();
        var incompatible = new System.Collections.Generic.HashSet<string>(StringComparer.Ordinal);
        foreach (var analysis in analyses)
        {
            cancellationToken.ThrowIfCancellationRequested();
            foreach (var promoted in analysis.PromotedModels)
            {
                cancellationToken.ThrowIfCancellationRequested();
                var key = promoted.Model.ModelTypeName;
                if (explicitRoots.Contains(key))
                {
                    continue;
                }

                if (deduped.TryGetValue(key, out var existing))
                {
                    if (!existing.Equals(promoted) && incompatible.Add(key))
                    {
                        diagnostics.Add(
                            new SparseGenerationResult(
                                null,
                                null,
                                ImmutableArray.Create(
                                    new SparseGeneratorDiagnostic(
                                        SparseDiagnosticIds.IncompatiblePromotedModel,
                                        null,
                                        promoted.Model.Name
                                    )
                                )
                            )
                        );
                    }

                    continue;
                }

                deduped.Add(key, promoted);
            }
        }

        var results = ImmutableArray.CreateBuilder<SparseGenerationResult>();
        foreach (var diagnostic in diagnostics)
        {
            results.Add(diagnostic);
        }

        foreach (var promoted in deduped.Values)
        {
            cancellationToken.ThrowIfCancellationRequested();
            if (incompatible.Contains(promoted.Model.ModelTypeName))
            {
                continue;
            }

            if (
                promoted.Members.Any(static member =>
                    member.Property.Name is "JsonConverter" or "FragmentJsonConverter"
                )
            )
            {
                var colliding = promoted.Members.First(member =>
                    member.Property.Name is "JsonConverter" or "FragmentJsonConverter"
                );
                results.Add(
                    new SparseGenerationResult(
                        null,
                        null,
                        ImmutableArray.Create(
                            new SparseGeneratorDiagnostic(
                                SparseDiagnosticIds.GeneratedNameCollision,
                                null,
                                colliding.Property.Name
                            )
                        )
                    )
                );
                continue;
            }

            var hint = SparseFragmentEmitter.GetPromotedHintName(promoted.Model, cancellationToken);
            var source = SparseFragmentEmitter.BuildPromotedSource(
                promoted,
                bclHashSetImplementsReadOnlySet,
                bclHashSetSupportsCapacity,
                cancellationToken
            );
            results.Add(
                new SparseGenerationResult(
                    hint,
                    source,
                    ImmutableArray<SparseGeneratorDiagnostic>.Empty
                )
            );
        }

        return results.ToImmutable();
    }
}
