using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace SparseFragments.Generator.Shared;

/// <summary>Builds standalone generated source for a <c>[SparseFragmentModel]</c>.</summary>
internal static class SparseFragmentEmitter
{
    private const string Optional = SparseWellKnownNames.OptionalType;
    private const string MergeStrategy = SparseWellKnownNames.MergeStrategyType;
    private const string ReferenceComparer = SparseWellKnownNames.ReferenceComparerType;

    public static string BuildSource(
        SparseModelInfo model,
        ImmutableArray<SparseMemberModel> members,
        ImmutableArray<SparsePocoCloneModel> pocoCloneModels,
        ImmutableArray<SparseStructuralModel> structuralModels,
        bool bclHashSetImplementsReadOnlySet,
        bool bclHashSetSupportsCapacity,
        CancellationToken cancellationToken
    )
    {
        return BuildSourceInternal(
            model,
            members,
            pocoCloneModels,
            structuralModels,
            bclHashSetImplementsReadOnlySet,
            bclHashSetSupportsCapacity,
            emitModelExtensions: true,
            cancellationToken
        );
    }

    public static string BuildPromotedSource(
        SparsePromotedModel promoted,
        bool bclHashSetImplementsReadOnlySet,
        bool bclHashSetSupportsCapacity,
        CancellationToken cancellationToken
    )
    {
        return BuildSourceInternal(
            promoted.Model,
            promoted.Members,
            promoted.PocoCloneModels,
            promoted.StructuralModels,
            bclHashSetImplementsReadOnlySet,
            bclHashSetSupportsCapacity,
            emitModelExtensions: false,
            cancellationToken
        );
    }

    public static string GetPromotedHintName(
        SparseModelInfo model,
        CancellationToken cancellationToken
    )
    {
        var fullyQualifiedName = model.ModelTypeName;
        return SparseNaming.Sanitize(fullyQualifiedName, cancellationToken)
            + "_"
            + SparseNaming.GetStableTypeHash(fullyQualifiedName, cancellationToken)
            + ".SparsePromoted.g.cs";
    }

    private static string BuildSourceInternal(
        SparseModelInfo model,
        ImmutableArray<SparseMemberModel> members,
        ImmutableArray<SparsePocoCloneModel> pocoCloneModels,
        ImmutableArray<SparseStructuralModel> structuralModels,
        bool bclHashSetImplementsReadOnlySet,
        bool bclHashSetSupportsCapacity,
        bool emitModelExtensions,
        CancellationToken cancellationToken
    )
    {
        cancellationToken.ThrowIfCancellationRequested();
        _ = structuralModels;
        var portableSetView = SparseFragmentCoreEmitter.RequiresPortableSetView(
            bclHashSetImplementsReadOnlySet,
            members
                .Select(static member => member.Collection.NamedTypeDefinition)
                .Concat(
                    pocoCloneModels.SelectMany(static poco =>
                        poco.Members.Select(static member => member.Collection.NamedTypeDefinition)
                    )
                )
        );
        if (portableSetView)
        {
            members = ApplyPortableSetView(members);
            pocoCloneModels = pocoCloneModels
                .Select(static poco => poco with { Members = ApplyPortableSetView(poco.Members) })
                .ToImmutableArray();
        }

        var modelType = model.ModelTypeName;
        var generatedType = ModelDeclarationKeyword(model);
        var name = SparseNaming.EscapeIdentifier(model.Name);
        var code = new SharedIndentedBuilder(cancellationToken);
        code.AppendLine("// <auto-generated />");
        code.AppendLine("#nullable enable");
        if (!model.IsGlobalNamespace)
        {
            code.Append("namespace ").Append(model.Namespace).AppendLine(";");
        }

        code.Append(generatedType).Append(name).AppendLine();
        code.AppendLine("{");
        SparseFragmentCoreEmitter.AppendRootProjectionConstructor(
            code,
            name,
            members,
            model.Constructor
        );
        Core.AppendDeepClone(
            code,
            modelType,
            members,
            !pocoCloneModels.IsEmpty,
            model.Constructor,
            !model.IsStruct
        );
        foreach (var poco in pocoCloneModels)
            Core.AppendPocoCloneHelper(
                code,
                poco.Model.ModelTypeName,
                poco.CloneHelperName,
                poco.Members,
                poco.Model.Constructor
            );
        SparseFragmentCoreEmitter.AppendCollectionCloneHelpers(
            code,
            portableSetView,
            bclHashSetSupportsCapacity
        );
        AppendFragment(
            code,
            modelType,
            members,
            !model.IsStruct,
            !pocoCloneModels.IsEmpty,
            constructor: model.Constructor,
            hashSetSupportsCapacity: bclHashSetSupportsCapacity
        );
        if (!model.IsStruct)
        {
            SparseObservableEmitter.AppendObservable(code, modelType, members);
        }

        code.AppendLine("}");
        if (emitModelExtensions)
        {
            SparseModelExtensionsEmitter.Append(code, model, members);
        }

        return code.ToString();
    }

    private static ImmutableArray<SparseMemberModel> ApplyPortableSetView(
        ImmutableArray<SparseMemberModel> members
    ) => members.Select(static member => member with { PortableSetView = true }).ToImmutableArray();

    private static string ModelDeclarationKeyword(SparseModelInfo model)
    {
        if (model.IsStruct)
        {
            return model.IsRecord ? "partial record struct " : "partial struct ";
        }

        return model.IsRecord ? "partial record class " : "partial class ";
    }

    private static void AppendFragment(
        SharedIndentedBuilder code,
        string modelType,
        ImmutableArray<SparseMemberModel> members,
        bool modelIsReferenceType,
        bool usesPocoCloning,
        bool isRootModel = true,
        ModelConstructorBinding? constructor = null,
        bool hashSetSupportsCapacity = false
    )
    {
        SparseFragmentCoreEmitter.AppendDeclaration(code, string.Empty, string.Empty);
        Core.AppendMembers(code, members, MergeStrategy);
        code.AppendLineAt(2, "/// <summary>The empty fragment.</summary>");
        code.AppendLineAt(2, "public static Fragment Empty { get; } = new();");
        AppendFragmentEquality(code, members);
        Core.AppendFromModel(code, modelType, members, modelIsReferenceType, usesPocoCloning);
        SparseFragmentCoreEmitter.AppendToModel(code, modelType, members, isRootModel, constructor);
        Core.AppendMerge(code, members);
        Core.AppendApplyChanges(code, members);
        Core.AppendDiff(code, modelType, members, modelIsReferenceType);
        Core.AppendFragmentClone(code, members, usesPocoCloning);
        SparseFragmentPatchEmitter.AppendFragmentMethods(code, modelType);
        code.AppendLineAt(2, "public FragmentBuilder ToBuilder() => new(this);");
        SparseFragmentJsonEmitter.AppendStandaloneFragmentJson(code, members, Optional);
        code.AppendLineAt(1, "}");
        Core.AppendBuilder(code, members);
        SparseFragmentPatchEmitter.AppendPatch(code, modelType, members, hashSetSupportsCapacity);
    }

    private static void AppendFragmentEquality(
        SharedIndentedBuilder code,
        ImmutableArray<SparseMemberModel> members
    )
    {
        code.CancellationToken.ThrowIfCancellationRequested();
        code.AppendLineAt(
            2,
            "internal static bool __SparseAreEqual(global::SparseFragments.Optional<Fragment?> left, global::SparseFragments.Optional<Fragment?> right)"
        );
        code.AppendLineAt(2, "{");
        code.AppendLineAt(3, "if (!left.IsPresent) return !right.IsPresent;");
        code.AppendLineAt(3, "if (!right.IsPresent) return false;");
        code.AppendLineAt(
            3,
            "if (global::System.Object.ReferenceEquals(left.Value, right.Value)) return true;"
        );
        code.AppendLineAt(3, "if (left.Value is null || right.Value is null) return false;");
        if (members.IsEmpty)
        {
            code.AppendLineAt(3, "return true;");
        }
        else
        {
            code.AppendIndent(3).Append("return ");
            for (var index = 0; index < members.Length; index++)
            {
                if (index > 0)
                {
                    code.Append(" && ");
                }

                var name = SparseNaming.EscapeIdentifier(members[index].Property.Name);
                code.Append("__SparseEqual_")
                    .Append(members[index].Id)
                    .Append("(left.Value.")
                    .Append(name)
                    .Append(", right.Value.")
                    .Append(name)
                    .Append(")");
            }
            code.AppendLine(";");
        }
        code.AppendLineAt(2, "}");
        foreach (var member in members)
        {
            var valueType = SparseFragmentEmitHelpers.FragmentValueType(member);
            code.AppendIndent(2)
                .Append("internal static bool __SparseEqual_")
                .Append(member.Id)
                .Append("(global::SparseFragments.Optional<")
                .Append(valueType)
                .Append("> left, global::SparseFragments.Optional<")
                .Append(valueType)
                .AppendLine("> right)");
            code.AppendLineAt(2, "{");
            code.AppendLineAt(3, "if (!left.IsPresent) return !right.IsPresent;");
            code.AppendLineAt(3, "if (!right.IsPresent) return false;");
            string equality;
            if (member.ChildModel is not null)
            {
                equality = member.ChildFragmentType + ".__SparseAreEqual(left, right)";
            }
            else if (member.MergeStrategyType is not null)
            {
                equality = Core.MergeStrategyField(member) + ".AreEqual(left.Value, right.Value)";
            }
            else
            {
                equality = Expressions.ValueEqualityExpression(member, "left.Value", "right.Value");
            }
            code.AppendLineAt(3, "return " + equality + ";");
            code.AppendLineAt(2, "}");
        }
        code.AppendLine();
    }

    private static readonly SparseFragmentExpressions Expressions = new("__sparse_clone_context");

    private static readonly SparseFragmentCoreEmitter Core = new(
        Optional,
        SparseWellKnownNames.MergeStrategyFieldPrefix,
        "__sparse_clone_context",
        ReferenceComparer,
        Expressions
    );
}
