using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace SparseFragments.Generator.Shared;

/// <summary>Builds standalone generated source for a <c>[SparseFragmentModel]</c>.</summary>
internal static class SparseFragmentEmitter
{
    private const string Runtime = SparseWellKnownNames.RuntimeNamespace;
    private const string Optional = SparseWellKnownNames.OptionalType;
    private const string FragmentMember = SparseWellKnownNames.FragmentMemberType;
    private const string FragmentInterface = SparseWellKnownNames.FragmentInterfaceType;
    private const string FragmentOfT = SparseWellKnownNames.FragmentInterfaceType;
    private const string DeepCloneable = SparseWellKnownNames.DeepCloneableType;
    private const string Schema = SparseWellKnownNames.SchemaType;
    private const string MemberSchema = SparseWellKnownNames.MemberSchemaType;
    private const string MergeStrategy = SparseWellKnownNames.MergeStrategyType;
    private const string ReferenceComparer = SparseWellKnownNames.ReferenceComparerType;

    public static string BuildSource(
        SparseModelInfo model,
        ImmutableArray<SparseMemberModel> members,
        ImmutableArray<SparsePocoCloneModel> pocoCloneModels,
        ImmutableArray<SparseStructuralModel> structuralModels,
        bool bclHashSetImplementsReadOnlySet,
        bool bclHashSetSupportsCapacity,
        CancellationToken cancellationToken
    )
    {
        return BuildSourceInternal(
            model,
            members,
            pocoCloneModels,
            structuralModels,
            bclHashSetImplementsReadOnlySet,
            bclHashSetSupportsCapacity,
            cancellationToken
        );
    }

    public static string BuildPromotedSource(
        SparsePromotedModel promoted,
        bool bclHashSetImplementsReadOnlySet,
        bool bclHashSetSupportsCapacity,
        CancellationToken cancellationToken
    )
    {
        return BuildSourceInternal(
            promoted.Model,
            promoted.Members,
            promoted.PocoCloneModels,
            promoted.StructuralModels,
            bclHashSetImplementsReadOnlySet,
            bclHashSetSupportsCapacity,
            cancellationToken
        );
    }

    public static string GetPromotedHintName(
        SparseModelInfo model,
        CancellationToken cancellationToken
    )
    {
        var fullyQualifiedName = model.ModelTypeName;
        return SparseNaming.Sanitize(fullyQualifiedName, cancellationToken)
            + "_"
            + SparseNaming.GetStableTypeHash(fullyQualifiedName, cancellationToken)
            + ".SparsePromoted.g.cs";
    }

    private static string BuildSourceInternal(
        SparseModelInfo model,
        ImmutableArray<SparseMemberModel> members,
        ImmutableArray<SparsePocoCloneModel> pocoCloneModels,
        ImmutableArray<SparseStructuralModel> structuralModels,
        bool bclHashSetImplementsReadOnlySet,
        bool bclHashSetSupportsCapacity,
        CancellationToken cancellationToken
    )
    {
        cancellationToken.ThrowIfCancellationRequested();
        var portableSetView = SparseFragmentCoreEmitter.RequiresPortableSetView(
            bclHashSetImplementsReadOnlySet,
            members
                .Select(static member => member.Collection.NamedTypeDefinition)
                .Concat(
                    pocoCloneModels.SelectMany(static poco =>
                        poco.Members.Select(static member => member.Collection.NamedTypeDefinition)
                    )
                )
                .Concat(
                    structuralModels.SelectMany(static structural =>
                        structural.Members.Select(static member =>
                            member.Collection.NamedTypeDefinition
                        )
                    )
                )
        );
        if (portableSetView)
        {
            members = ApplyPortableSetView(members);
            pocoCloneModels = pocoCloneModels
                .Select(static poco => poco with { Members = ApplyPortableSetView(poco.Members) })
                .ToImmutableArray();
            structuralModels = structuralModels
                .Select(static structural =>
                    structural with
                    {
                        Members = ApplyPortableSetView(structural.Members),
                    }
                )
                .ToImmutableArray();
        }

        var modelType = model.ModelTypeName;
        var generatedType = ModelDeclarationKeyword(model);
        var name = SparseNaming.EscapeIdentifier(model.Name);
        var code = new SharedIndentedBuilder(cancellationToken);
        code.AppendLine("// <auto-generated />");
        code.AppendLine("#nullable enable");
        if (!model.IsGlobalNamespace)
        {
            code.Append("namespace ").Append(model.Namespace).AppendLine(";");
        }

        code.Append(generatedType)
            .Append(name)
            .Append(" : ")
            .Append(DeepCloneable)
            .Append("<")
            .Append(modelType)
            .AppendLine(">");
        code.AppendLine("{");
        SparseFragmentCoreEmitter.AppendRootProjectionConstructor(
            code,
            name,
            members,
            model.Constructor
        );
        Core.AppendDeepClone(
            code,
            modelType,
            members,
            !pocoCloneModels.IsEmpty,
            model.Constructor,
            !model.IsStruct
        );
        foreach (var poco in pocoCloneModels)
            Core.AppendPocoCloneHelper(
                code,
                poco.Model.ModelTypeName,
                poco.CloneHelperName,
                poco.Members,
                poco.Model.Constructor
            );
        SparseFragmentCoreEmitter.AppendCollectionCloneHelpers(
            code,
            portableSetView,
            bclHashSetSupportsCapacity
        );
        AppendFragment(
            code,
            modelType,
            members,
            !model.IsStruct,
            !pocoCloneModels.IsEmpty,
            constructor: model.Constructor
        );
        AppendStructuralModels(code, structuralModels, !pocoCloneModels.IsEmpty);
        code.AppendLine("}");
        return code.ToString();
    }

    private static ImmutableArray<SparseMemberModel> ApplyPortableSetView(
        ImmutableArray<SparseMemberModel> members
    ) => members.Select(static member => member with { PortableSetView = true }).ToImmutableArray();

    private static string ModelDeclarationKeyword(SparseModelInfo model)
    {
        if (model.IsStruct)
        {
            return model.IsRecord ? "partial record struct " : "partial struct ";
        }

        return model.IsRecord ? "partial record class " : "partial class ";
    }

    private static void AppendStructuralModels(
        SharedIndentedBuilder code,
        ImmutableArray<SparseStructuralModel> structuralModels,
        bool usesPocoCloning
    )
    {
        code.CancellationToken.ThrowIfCancellationRequested();
        foreach (var structuralModel in structuralModels)
        {
            code.AppendLineAt(
                1,
                "/// <summary>Generated shape for an undecorated structural member type.</summary>"
            );
            code.AppendLineAt(1, "public sealed class " + structuralModel.HostName);
            code.AppendLineAt(1, "{");
            code.IndentOffset++;
            AppendFragment(
                code,
                structuralModel.ValueTypeName,
                structuralModel.Members,
                true,
                usesPocoCloning,
                isRootModel: false,
                emitJsonBridge: false,
                constructor: structuralModel.Constructor
            );
            code.IndentOffset--;
            code.AppendLineAt(1, "}");
        }
    }

    private static void AppendFragment(
        SharedIndentedBuilder code,
        string modelType,
        ImmutableArray<SparseMemberModel> members,
        bool modelIsReferenceType,
        bool usesPocoCloning,
        bool isRootModel = true,
        bool emitJsonBridge = true,
        ModelConstructorBinding? constructor = null
    )
    {
        SparseFragmentCoreEmitter.AppendDeclaration(code, FragmentOfT, DeepCloneable);
        Core.AppendMembers(code, members, MergeStrategy);
        AppendFragmentDescriptor(code, modelType, members);
        Core.AppendFromModel(code, modelType, members, modelIsReferenceType, usesPocoCloning);
        SparseFragmentCoreEmitter.AppendToModel(code, modelType, members, isRootModel, constructor);
        Core.AppendMerge(code, members);
        Core.AppendApplyChanges(code, members);
        Core.AppendDiff(code, modelType, members, modelIsReferenceType);
        Core.AppendFragmentClone(code, members, usesPocoCloning);
        SparseFragmentPatchEmitter.AppendFragmentMethods(code, modelType);
        code.AppendLineAt(2, "public FragmentBuilder ToBuilder() => new(this);");
        SparseJsonPatchEmitter.AppendStandaloneFragmentJson(code, members, Optional);
        code.AppendLineAt(1, "}");
        Core.AppendBuilder(code, members);
        SparseFragmentPatchEmitter.AppendPatch(code, modelType, members, emitJsonBridge);
    }

    private static void AppendFragmentDescriptor(
        SharedIndentedBuilder code,
        string modelType,
        ImmutableArray<SparseMemberModel> members
    )
    {
        code.CancellationToken.ThrowIfCancellationRequested();
        code.AppendLineAt(2, "/// <summary>The empty fragment.</summary>");
        code.AppendLineAt(2, "public static Fragment Empty { get; } = new();");
        code.AppendIndent(2)
            .Append("public static ")
            .Append(Schema)
            .Append(" FragmentSchema { get; } = new(typeof(")
            .Append(modelType)
            .AppendLine("), new " + MemberSchema + "[]");
        code.AppendLineAt(2, "{");
        foreach (var member in members)
        {
            var valueType = member.ChildModel is null
                ? member.Property.Type.NonNullableName
                : member.ChildFragmentType!;
            code.AppendIndent(3)
                .Append("new(")
                .Append(member.Id)
                .Append(", ")
                .Append(SymbolDisplay.FormatLiteral(member.Property.Name, true))
                .Append(", typeof(")
                .Append(valueType)
                .Append("), ")
                .Append(Runtime)
                .Append(".MergeMode.")
                .Append(SparseNaming.MergeModeName(member.MergeMode))
                .Append(", static value => ((")
                .Append(modelType)
                .Append(")value).")
                .Append(SparseNaming.EscapeIdentifier(member.Property.Name))
                .Append(", ");
            if (member.ChildModel is null)
            {
                code.Append("null");
            }
            else
            {
                code.Append("static () => ")
                    .Append(member.ChildFragmentType!)
                    .Append(".FragmentSchema!");
            }

            code.Append(", ")
                .Append(member.MergeStrategyType is null ? "null" : Core.MergeStrategyField(member))
                .Append(", static () => default(")
                .Append(member.Property.Type.Name)
                .Append("), ");
            code.Append(
                member.Collection.Kind == SparseCollectionKind.Unsupported
                    ? "null"
                    : "static values => "
                        + SparseFragmentExpressions.MaterializeCollection(
                            member,
                            "global::System.Linq.Enumerable.Cast<"
                                + member.Collection.ElementType.Name
                                + ">(values)"
                        )
            );
            code.Append(")");
            if (member.Collection.Kind == SparseCollectionKind.Set)
                code.Append(" { ContainsElement = static (values, element) => ((")
                    .Append(member.Property.Type.Name)
                    .Append(")values).Contains((")
                    .Append(member.Collection.ElementType.Name)
                    .Append(")element!) }");
            code.AppendLine(",");
        }

        code.AppendLineAt(2, "}, static () => Fragment.Empty);");
        code.AppendIndent(2)
            .Append("public ")
            .Append(Schema)
            .AppendLine(" Schema => FragmentSchema;");
        code.AppendLineAt(
            2,
            "public global::System.Collections.Generic.IEnumerable<"
                + FragmentMember
                + "> EnumeratePresentMembers()"
        );
        code.AppendLineAt(2, "{");
        foreach (var member in members)
        {
            var name = SparseNaming.EscapeIdentifier(member.Property.Name);
            code.AppendIndent(3)
                .Append("if (")
                .Append(name)
                .Append(".IsPresent) yield return new(")
                .Append(member.Id)
                .Append(", ")
                .Append(SymbolDisplay.FormatLiteral(member.Property.Name, true))
                .Append(", ")
                .Append(name)
                .AppendLine(".Value);");
        }

        code.AppendLineAt(2, "}");
        AppendWithMember(code, members);
        AppendWithoutMember(code, members);
        code.AppendLine();
    }

    private static void AppendWithMember(
        SharedIndentedBuilder code,
        ImmutableArray<SparseMemberModel> members
    )
    {
        code.AppendIndent(2)
            .Append("public ")
            .Append(FragmentInterface)
            .AppendLine(" WithMember(int memberId, object? value)");
        code.AppendLineAt(2, "{");
        code.AppendLineAt(3, "switch (memberId)");
        code.AppendLineAt(3, "{");
        foreach (var member in members)
        {
            var name = SparseNaming.EscapeIdentifier(member.Property.Name);
            code.AppendIndent(4).Append("case ").Append(member.Id).AppendLine(":");
            code.AppendIndent(5).Append("return new Fragment");
            code.AppendLine();
            code.AppendLineAt(5, "{");
            foreach (var copy in members)
            {
                var copyName = SparseNaming.EscapeIdentifier(copy.Property.Name);
                code.AppendIndent(6)
                    .Append(copyName)
                    .Append(" = ")
                    .Append(
                        copyName == name
                            ? Optional
                                + "<"
                                + FragmentValueType(copy)
                                + ">.Present(("
                                + FragmentValueType(copy)
                                + ")value!)"
                            : "this." + copyName
                    )
                    .AppendLine(",");
            }

            code.AppendLineAt(5, "};");
        }

        code.AppendLineAt(
            4,
            "default: throw new global::System.ArgumentOutOfRangeException(nameof(memberId));"
        );
        code.AppendLineAt(3, "}");
        code.AppendLineAt(2, "}");
    }

    private static void AppendWithoutMember(
        SharedIndentedBuilder code,
        ImmutableArray<SparseMemberModel> members
    )
    {
        code.AppendIndent(2)
            .Append("public ")
            .Append(FragmentInterface)
            .AppendLine(" WithoutMember(int memberId)");
        code.AppendLineAt(2, "{");
        code.AppendLineAt(3, "switch (memberId)");
        code.AppendLineAt(3, "{");
        foreach (var member in members)
        {
            var name = SparseNaming.EscapeIdentifier(member.Property.Name);
            code.AppendIndent(4).Append("case ").Append(member.Id).AppendLine(":");
            code.AppendIndent(5).Append("return new Fragment");
            code.AppendLine();
            code.AppendLineAt(5, "{");
            foreach (var copy in members)
            {
                var copyName = SparseNaming.EscapeIdentifier(copy.Property.Name);
                code.AppendIndent(6)
                    .Append(copyName)
                    .Append(" = ")
                    .Append(copyName == name ? "default" : "this." + copyName)
                    .AppendLine(",");
            }

            code.AppendLineAt(5, "};");
        }

        code.AppendLineAt(
            4,
            "default: throw new global::System.ArgumentOutOfRangeException(nameof(memberId));"
        );
        code.AppendLineAt(3, "}");
        code.AppendLineAt(2, "}");
    }

    private static string FragmentValueType(SparseMemberModel member) =>
        member.ChildModel is null ? member.Property.Type.Name : member.ChildFragmentType + "?";

    private static readonly SparseFragmentExpressions Expressions = new("__sparse_clone_context");

    private static readonly SparseFragmentCoreEmitter Core = new(
        Optional,
        SparseWellKnownNames.MergeStrategyFieldPrefix,
        "__sparse_clone_context",
        ReferenceComparer,
        Expressions
    );
}
