<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>SparseFragments.Tests</RootNamespace>
    <AssemblyName>SparseFragments.Tests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.8.0" />
    <ProjectReference Include="../../src/SparseFragments/SparseFragments.csproj" />
    <ProjectReference
      Include="../../src/SparseFragments.Generator/SparseFragments.Generator.csproj"
      OutputItemType="Analyzer"
      ReferenceOutputAssembly="true"
    />
  </ItemGroup>
  <ItemGroup>
    <Using Include="SparseFragments" />
  </ItemGroup>
</Project>
